/* automatically generated by rust-bindgen */

pub type ID3D11Debug = Struct_ID3D11Debug;
pub type ID3D11SwitchToRef = Struct_ID3D11SwitchToRef;
pub type ID3D11InfoQueue = Struct_ID3D11InfoQueue;
pub type Enum_D3D11_RLDO_FLAGS = ::libc::c_uint;
pub const D3D11_RLDO_SUMMARY: ::libc::c_uint = 1;
pub const D3D11_RLDO_DETAIL: ::libc::c_uint = 2;
pub type D3D11_RLDO_FLAGS = Enum_D3D11_RLDO_FLAGS;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ID3D11DebugVtbl {
    pub QueryInterface: ::std::option::Option<extern "C" fn
                                                  (This: *mut ID3D11Debug,
                                                   riid: *const IID,
                                                   ppvObject:
                                                       *mut *mut ::libc::c_void)
                                                  -> HRESULT>,
    pub AddRef: ::std::option::Option<extern "C" fn(This: *mut ID3D11Debug)
                                          -> ULONG>,
    pub Release: ::std::option::Option<extern "C" fn(This: *mut ID3D11Debug)
                                           -> ULONG>,
    pub SetFeatureMask: ::std::option::Option<extern "C" fn
                                                  (This: *mut ID3D11Debug,
                                                   Mask: UINT) -> HRESULT>,
    pub GetFeatureMask: ::std::option::Option<extern "C" fn
                                                  (This: *mut ID3D11Debug)
                                                  -> UINT>,
    pub SetPresentPerRenderOpDelay: ::std::option::Option<extern "C" fn
                                                              (This:
                                                                   *mut ID3D11Debug,
                                                               Milliseconds:
                                                                   UINT)
                                                              -> HRESULT>,
    pub GetPresentPerRenderOpDelay: ::std::option::Option<extern "C" fn
                                                              (This:
                                                                   *mut ID3D11Debug)
                                                              -> UINT>,
    pub SetSwapChain: ::std::option::Option<extern "C" fn
                                                (This: *mut ID3D11Debug,
                                                 pSwapChain:
                                                     *mut IDXGISwapChain)
                                                -> HRESULT>,
    pub GetSwapChain: ::std::option::Option<extern "C" fn
                                                (This: *mut ID3D11Debug,
                                                 ppSwapChain:
                                                     *mut *mut IDXGISwapChain)
                                                -> HRESULT>,
    pub ValidateContext: ::std::option::Option<extern "C" fn
                                                   (This: *mut ID3D11Debug,
                                                    pContext:
                                                        *mut ID3D11DeviceContext)
                                                   -> HRESULT>,
    pub ReportLiveDeviceObjects: ::std::option::Option<extern "C" fn
                                                           (This:
                                                                *mut ID3D11Debug,
                                                            Flags:
                                                                D3D11_RLDO_FLAGS)
                                                           -> HRESULT>,
    pub ValidateContextForDispatch: ::std::option::Option<extern "C" fn
                                                              (This:
                                                                   *mut ID3D11Debug,
                                                               pContext:
                                                                   *mut ID3D11DeviceContext)
                                                              -> HRESULT>,
}
impl ::std::default::Default for Struct_ID3D11DebugVtbl {
    fn default() -> Struct_ID3D11DebugVtbl { unsafe { ::std::mem::zeroed() } }
}
pub type ID3D11DebugVtbl = Struct_ID3D11DebugVtbl;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ID3D11Debug {
    pub lpVtbl: *mut Struct_ID3D11DebugVtbl,
}
impl ::std::default::Default for Struct_ID3D11Debug {
    fn default() -> Struct_ID3D11Debug { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ID3D11SwitchToRefVtbl {
    pub QueryInterface: ::std::option::Option<extern "C" fn
                                                  (This:
                                                       *mut ID3D11SwitchToRef,
                                                   riid: *const IID,
                                                   ppvObject:
                                                       *mut *mut ::libc::c_void)
                                                  -> HRESULT>,
    pub AddRef: ::std::option::Option<extern "C" fn
                                          (This: *mut ID3D11SwitchToRef)
                                          -> ULONG>,
    pub Release: ::std::option::Option<extern "C" fn
                                           (This: *mut ID3D11SwitchToRef)
                                           -> ULONG>,
    pub SetUseRef: ::std::option::Option<extern "C" fn
                                             (This: *mut ID3D11SwitchToRef,
                                              UseRef: BOOL) -> BOOL>,
    pub GetUseRef: ::std::option::Option<extern "C" fn
                                             (This: *mut ID3D11SwitchToRef)
                                             -> BOOL>,
}
impl ::std::default::Default for Struct_ID3D11SwitchToRefVtbl {
    fn default() -> Struct_ID3D11SwitchToRefVtbl {
        unsafe { ::std::mem::zeroed() }
    }
}
pub type ID3D11SwitchToRefVtbl = Struct_ID3D11SwitchToRefVtbl;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ID3D11SwitchToRef {
    pub lpVtbl: *mut Struct_ID3D11SwitchToRefVtbl,
}
impl ::std::default::Default for Struct_ID3D11SwitchToRef {
    fn default() -> Struct_ID3D11SwitchToRef {
        unsafe { ::std::mem::zeroed() }
    }
}
pub type Enum_D3D11_MESSAGE_CATEGORY = ::libc::c_uint;
pub const D3D11_MESSAGE_CATEGORY_APPLICATION_DEFINED: ::libc::c_uint = 0;
pub const D3D11_MESSAGE_CATEGORY_MISCELLANEOUS: ::libc::c_uint = 1;
pub const D3D11_MESSAGE_CATEGORY_INITIALIZATION: ::libc::c_uint = 2;
pub const D3D11_MESSAGE_CATEGORY_CLEANUP: ::libc::c_uint = 3;
pub const D3D11_MESSAGE_CATEGORY_COMPILATION: ::libc::c_uint = 4;
pub const D3D11_MESSAGE_CATEGORY_STATE_CREATION: ::libc::c_uint = 5;
pub const D3D11_MESSAGE_CATEGORY_STATE_SETTING: ::libc::c_uint = 6;
pub const D3D11_MESSAGE_CATEGORY_STATE_GETTING: ::libc::c_uint = 7;
pub const D3D11_MESSAGE_CATEGORY_RESOURCE_MANIPULATION: ::libc::c_uint = 8;
pub const D3D11_MESSAGE_CATEGORY_EXECUTION: ::libc::c_uint = 9;
pub type D3D11_MESSAGE_CATEGORY = Enum_D3D11_MESSAGE_CATEGORY;
pub type Enum_D3D11_MESSAGE_SEVERITY = ::libc::c_uint;
pub const D3D11_MESSAGE_SEVERITY_CORRUPTION: ::libc::c_uint = 0;
pub const D3D11_MESSAGE_SEVERITY_ERROR: ::libc::c_uint = 1;
pub const D3D11_MESSAGE_SEVERITY_WARNING: ::libc::c_uint = 2;
pub const D3D11_MESSAGE_SEVERITY_INFO: ::libc::c_uint = 3;
pub type D3D11_MESSAGE_SEVERITY = Enum_D3D11_MESSAGE_SEVERITY;
pub type Enum_D3D11_MESSAGE_ID = ::libc::c_uint;
pub const D3D11_MESSAGE_ID_UNKNOWN: ::libc::c_uint = 0;
pub const D3D11_MESSAGE_ID_DEVICE_IASETVERTEXBUFFERS_HAZARD: ::libc::c_uint =
    1;
pub const D3D11_MESSAGE_ID_DEVICE_IASETINDEXBUFFER_HAZARD: ::libc::c_uint = 2;
pub const D3D11_MESSAGE_ID_DEVICE_VSSETSHADERRESOURCES_HAZARD: ::libc::c_uint
          =
    3;
pub const D3D11_MESSAGE_ID_DEVICE_VSSETCONSTANTBUFFERS_HAZARD: ::libc::c_uint
          =
    4;
pub const D3D11_MESSAGE_ID_DEVICE_GSSETSHADERRESOURCES_HAZARD: ::libc::c_uint
          =
    5;
pub const D3D11_MESSAGE_ID_DEVICE_GSSETCONSTANTBUFFERS_HAZARD: ::libc::c_uint
          =
    6;
pub const D3D11_MESSAGE_ID_DEVICE_PSSETSHADERRESOURCES_HAZARD: ::libc::c_uint
          =
    7;
pub const D3D11_MESSAGE_ID_DEVICE_PSSETCONSTANTBUFFERS_HAZARD: ::libc::c_uint
          =
    8;
pub const D3D11_MESSAGE_ID_DEVICE_OMSETRENDERTARGETS_HAZARD: ::libc::c_uint =
    9;
pub const D3D11_MESSAGE_ID_DEVICE_SOSETTARGETS_HAZARD: ::libc::c_uint = 10;
pub const D3D11_MESSAGE_ID_STRING_FROM_APPLICATION: ::libc::c_uint = 11;
pub const D3D11_MESSAGE_ID_CORRUPTED_THIS: ::libc::c_uint = 12;
pub const D3D11_MESSAGE_ID_CORRUPTED_PARAMETER1: ::libc::c_uint = 13;
pub const D3D11_MESSAGE_ID_CORRUPTED_PARAMETER2: ::libc::c_uint = 14;
pub const D3D11_MESSAGE_ID_CORRUPTED_PARAMETER3: ::libc::c_uint = 15;
pub const D3D11_MESSAGE_ID_CORRUPTED_PARAMETER4: ::libc::c_uint = 16;
pub const D3D11_MESSAGE_ID_CORRUPTED_PARAMETER5: ::libc::c_uint = 17;
pub const D3D11_MESSAGE_ID_CORRUPTED_PARAMETER6: ::libc::c_uint = 18;
pub const D3D11_MESSAGE_ID_CORRUPTED_PARAMETER7: ::libc::c_uint = 19;
pub const D3D11_MESSAGE_ID_CORRUPTED_PARAMETER8: ::libc::c_uint = 20;
pub const D3D11_MESSAGE_ID_CORRUPTED_PARAMETER9: ::libc::c_uint = 21;
pub const D3D11_MESSAGE_ID_CORRUPTED_PARAMETER10: ::libc::c_uint = 22;
pub const D3D11_MESSAGE_ID_CORRUPTED_PARAMETER11: ::libc::c_uint = 23;
pub const D3D11_MESSAGE_ID_CORRUPTED_PARAMETER12: ::libc::c_uint = 24;
pub const D3D11_MESSAGE_ID_CORRUPTED_PARAMETER13: ::libc::c_uint = 25;
pub const D3D11_MESSAGE_ID_CORRUPTED_PARAMETER14: ::libc::c_uint = 26;
pub const D3D11_MESSAGE_ID_CORRUPTED_PARAMETER15: ::libc::c_uint = 27;
pub const D3D11_MESSAGE_ID_CORRUPTED_MULTITHREADING: ::libc::c_uint = 28;
pub const D3D11_MESSAGE_ID_MESSAGE_REPORTING_OUTOFMEMORY: ::libc::c_uint = 29;
pub const D3D11_MESSAGE_ID_IASETINPUTLAYOUT_UNBINDDELETINGOBJECT:
          ::libc::c_uint =
    30;
pub const D3D11_MESSAGE_ID_IASETVERTEXBUFFERS_UNBINDDELETINGOBJECT:
          ::libc::c_uint =
    31;
pub const D3D11_MESSAGE_ID_IASETINDEXBUFFER_UNBINDDELETINGOBJECT:
          ::libc::c_uint =
    32;
pub const D3D11_MESSAGE_ID_VSSETSHADER_UNBINDDELETINGOBJECT: ::libc::c_uint =
    33;
pub const D3D11_MESSAGE_ID_VSSETSHADERRESOURCES_UNBINDDELETINGOBJECT:
          ::libc::c_uint =
    34;
pub const D3D11_MESSAGE_ID_VSSETCONSTANTBUFFERS_UNBINDDELETINGOBJECT:
          ::libc::c_uint =
    35;
pub const D3D11_MESSAGE_ID_VSSETSAMPLERS_UNBINDDELETINGOBJECT: ::libc::c_uint
          =
    36;
pub const D3D11_MESSAGE_ID_GSSETSHADER_UNBINDDELETINGOBJECT: ::libc::c_uint =
    37;
pub const D3D11_MESSAGE_ID_GSSETSHADERRESOURCES_UNBINDDELETINGOBJECT:
          ::libc::c_uint =
    38;
pub const D3D11_MESSAGE_ID_GSSETCONSTANTBUFFERS_UNBINDDELETINGOBJECT:
          ::libc::c_uint =
    39;
pub const D3D11_MESSAGE_ID_GSSETSAMPLERS_UNBINDDELETINGOBJECT: ::libc::c_uint
          =
    40;
pub const D3D11_MESSAGE_ID_SOSETTARGETS_UNBINDDELETINGOBJECT: ::libc::c_uint =
    41;
pub const D3D11_MESSAGE_ID_PSSETSHADER_UNBINDDELETINGOBJECT: ::libc::c_uint =
    42;
pub const D3D11_MESSAGE_ID_PSSETSHADERRESOURCES_UNBINDDELETINGOBJECT:
          ::libc::c_uint =
    43;
pub const D3D11_MESSAGE_ID_PSSETCONSTANTBUFFERS_UNBINDDELETINGOBJECT:
          ::libc::c_uint =
    44;
pub const D3D11_MESSAGE_ID_PSSETSAMPLERS_UNBINDDELETINGOBJECT: ::libc::c_uint
          =
    45;
pub const D3D11_MESSAGE_ID_RSSETSTATE_UNBINDDELETINGOBJECT: ::libc::c_uint =
    46;
pub const D3D11_MESSAGE_ID_OMSETBLENDSTATE_UNBINDDELETINGOBJECT:
          ::libc::c_uint =
    47;
pub const D3D11_MESSAGE_ID_OMSETDEPTHSTENCILSTATE_UNBINDDELETINGOBJECT:
          ::libc::c_uint =
    48;
pub const D3D11_MESSAGE_ID_OMSETRENDERTARGETS_UNBINDDELETINGOBJECT:
          ::libc::c_uint =
    49;
pub const D3D11_MESSAGE_ID_SETPREDICATION_UNBINDDELETINGOBJECT: ::libc::c_uint
          =
    50;
pub const D3D11_MESSAGE_ID_GETPRIVATEDATA_MOREDATA: ::libc::c_uint = 51;
pub const D3D11_MESSAGE_ID_SETPRIVATEDATA_INVALIDFREEDATA: ::libc::c_uint =
    52;
pub const D3D11_MESSAGE_ID_SETPRIVATEDATA_INVALIDIUNKNOWN: ::libc::c_uint =
    53;
pub const D3D11_MESSAGE_ID_SETPRIVATEDATA_INVALIDFLAGS: ::libc::c_uint = 54;
pub const D3D11_MESSAGE_ID_SETPRIVATEDATA_CHANGINGPARAMS: ::libc::c_uint = 55;
pub const D3D11_MESSAGE_ID_SETPRIVATEDATA_OUTOFMEMORY: ::libc::c_uint = 56;
pub const D3D11_MESSAGE_ID_CREATEBUFFER_UNRECOGNIZEDFORMAT: ::libc::c_uint =
    57;
pub const D3D11_MESSAGE_ID_CREATEBUFFER_INVALIDSAMPLES: ::libc::c_uint = 58;
pub const D3D11_MESSAGE_ID_CREATEBUFFER_UNRECOGNIZEDUSAGE: ::libc::c_uint =
    59;
pub const D3D11_MESSAGE_ID_CREATEBUFFER_UNRECOGNIZEDBINDFLAGS: ::libc::c_uint
          =
    60;
pub const D3D11_MESSAGE_ID_CREATEBUFFER_UNRECOGNIZEDCPUACCESSFLAGS:
          ::libc::c_uint =
    61;
pub const D3D11_MESSAGE_ID_CREATEBUFFER_UNRECOGNIZEDMISCFLAGS: ::libc::c_uint
          =
    62;
pub const D3D11_MESSAGE_ID_CREATEBUFFER_INVALIDCPUACCESSFLAGS: ::libc::c_uint
          =
    63;
pub const D3D11_MESSAGE_ID_CREATEBUFFER_INVALIDBINDFLAGS: ::libc::c_uint = 64;
pub const D3D11_MESSAGE_ID_CREATEBUFFER_INVALIDINITIALDATA: ::libc::c_uint =
    65;
pub const D3D11_MESSAGE_ID_CREATEBUFFER_INVALIDDIMENSIONS: ::libc::c_uint =
    66;
pub const D3D11_MESSAGE_ID_CREATEBUFFER_INVALIDMIPLEVELS: ::libc::c_uint = 67;
pub const D3D11_MESSAGE_ID_CREATEBUFFER_INVALIDMISCFLAGS: ::libc::c_uint = 68;
pub const D3D11_MESSAGE_ID_CREATEBUFFER_INVALIDARG_RETURN: ::libc::c_uint =
    69;
pub const D3D11_MESSAGE_ID_CREATEBUFFER_OUTOFMEMORY_RETURN: ::libc::c_uint =
    70;
pub const D3D11_MESSAGE_ID_CREATEBUFFER_NULLDESC: ::libc::c_uint = 71;
pub const D3D11_MESSAGE_ID_CREATEBUFFER_INVALIDCONSTANTBUFFERBINDINGS:
          ::libc::c_uint =
    72;
pub const D3D11_MESSAGE_ID_CREATEBUFFER_LARGEALLOCATION: ::libc::c_uint = 73;
pub const D3D11_MESSAGE_ID_CREATETEXTURE1D_UNRECOGNIZEDFORMAT: ::libc::c_uint
          =
    74;
pub const D3D11_MESSAGE_ID_CREATETEXTURE1D_UNSUPPORTEDFORMAT: ::libc::c_uint =
    75;
pub const D3D11_MESSAGE_ID_CREATETEXTURE1D_INVALIDSAMPLES: ::libc::c_uint =
    76;
pub const D3D11_MESSAGE_ID_CREATETEXTURE1D_UNRECOGNIZEDUSAGE: ::libc::c_uint =
    77;
pub const D3D11_MESSAGE_ID_CREATETEXTURE1D_UNRECOGNIZEDBINDFLAGS:
          ::libc::c_uint =
    78;
pub const D3D11_MESSAGE_ID_CREATETEXTURE1D_UNRECOGNIZEDCPUACCESSFLAGS:
          ::libc::c_uint =
    79;
pub const D3D11_MESSAGE_ID_CREATETEXTURE1D_UNRECOGNIZEDMISCFLAGS:
          ::libc::c_uint =
    80;
pub const D3D11_MESSAGE_ID_CREATETEXTURE1D_INVALIDCPUACCESSFLAGS:
          ::libc::c_uint =
    81;
pub const D3D11_MESSAGE_ID_CREATETEXTURE1D_INVALIDBINDFLAGS: ::libc::c_uint =
    82;
pub const D3D11_MESSAGE_ID_CREATETEXTURE1D_INVALIDINITIALDATA: ::libc::c_uint
          =
    83;
pub const D3D11_MESSAGE_ID_CREATETEXTURE1D_INVALIDDIMENSIONS: ::libc::c_uint =
    84;
pub const D3D11_MESSAGE_ID_CREATETEXTURE1D_INVALIDMIPLEVELS: ::libc::c_uint =
    85;
pub const D3D11_MESSAGE_ID_CREATETEXTURE1D_INVALIDMISCFLAGS: ::libc::c_uint =
    86;
pub const D3D11_MESSAGE_ID_CREATETEXTURE1D_INVALIDARG_RETURN: ::libc::c_uint =
    87;
pub const D3D11_MESSAGE_ID_CREATETEXTURE1D_OUTOFMEMORY_RETURN: ::libc::c_uint
          =
    88;
pub const D3D11_MESSAGE_ID_CREATETEXTURE1D_NULLDESC: ::libc::c_uint = 89;
pub const D3D11_MESSAGE_ID_CREATETEXTURE1D_LARGEALLOCATION: ::libc::c_uint =
    90;
pub const D3D11_MESSAGE_ID_CREATETEXTURE2D_UNRECOGNIZEDFORMAT: ::libc::c_uint
          =
    91;
pub const D3D11_MESSAGE_ID_CREATETEXTURE2D_UNSUPPORTEDFORMAT: ::libc::c_uint =
    92;
pub const D3D11_MESSAGE_ID_CREATETEXTURE2D_INVALIDSAMPLES: ::libc::c_uint =
    93;
pub const D3D11_MESSAGE_ID_CREATETEXTURE2D_UNRECOGNIZEDUSAGE: ::libc::c_uint =
    94;
pub const D3D11_MESSAGE_ID_CREATETEXTURE2D_UNRECOGNIZEDBINDFLAGS:
          ::libc::c_uint =
    95;
pub const D3D11_MESSAGE_ID_CREATETEXTURE2D_UNRECOGNIZEDCPUACCESSFLAGS:
          ::libc::c_uint =
    96;
pub const D3D11_MESSAGE_ID_CREATETEXTURE2D_UNRECOGNIZEDMISCFLAGS:
          ::libc::c_uint =
    97;
pub const D3D11_MESSAGE_ID_CREATETEXTURE2D_INVALIDCPUACCESSFLAGS:
          ::libc::c_uint =
    98;
pub const D3D11_MESSAGE_ID_CREATETEXTURE2D_INVALIDBINDFLAGS: ::libc::c_uint =
    99;
pub const D3D11_MESSAGE_ID_CREATETEXTURE2D_INVALIDINITIALDATA: ::libc::c_uint
          =
    100;
pub const D3D11_MESSAGE_ID_CREATETEXTURE2D_INVALIDDIMENSIONS: ::libc::c_uint =
    101;
pub const D3D11_MESSAGE_ID_CREATETEXTURE2D_INVALIDMIPLEVELS: ::libc::c_uint =
    102;
pub const D3D11_MESSAGE_ID_CREATETEXTURE2D_INVALIDMISCFLAGS: ::libc::c_uint =
    103;
pub const D3D11_MESSAGE_ID_CREATETEXTURE2D_INVALIDARG_RETURN: ::libc::c_uint =
    104;
pub const D3D11_MESSAGE_ID_CREATETEXTURE2D_OUTOFMEMORY_RETURN: ::libc::c_uint
          =
    105;
pub const D3D11_MESSAGE_ID_CREATETEXTURE2D_NULLDESC: ::libc::c_uint = 106;
pub const D3D11_MESSAGE_ID_CREATETEXTURE2D_LARGEALLOCATION: ::libc::c_uint =
    107;
pub const D3D11_MESSAGE_ID_CREATETEXTURE3D_UNRECOGNIZEDFORMAT: ::libc::c_uint
          =
    108;
pub const D3D11_MESSAGE_ID_CREATETEXTURE3D_UNSUPPORTEDFORMAT: ::libc::c_uint =
    109;
pub const D3D11_MESSAGE_ID_CREATETEXTURE3D_INVALIDSAMPLES: ::libc::c_uint =
    110;
pub const D3D11_MESSAGE_ID_CREATETEXTURE3D_UNRECOGNIZEDUSAGE: ::libc::c_uint =
    111;
pub const D3D11_MESSAGE_ID_CREATETEXTURE3D_UNRECOGNIZEDBINDFLAGS:
          ::libc::c_uint =
    112;
pub const D3D11_MESSAGE_ID_CREATETEXTURE3D_UNRECOGNIZEDCPUACCESSFLAGS:
          ::libc::c_uint =
    113;
pub const D3D11_MESSAGE_ID_CREATETEXTURE3D_UNRECOGNIZEDMISCFLAGS:
          ::libc::c_uint =
    114;
pub const D3D11_MESSAGE_ID_CREATETEXTURE3D_INVALIDCPUACCESSFLAGS:
          ::libc::c_uint =
    115;
pub const D3D11_MESSAGE_ID_CREATETEXTURE3D_INVALIDBINDFLAGS: ::libc::c_uint =
    116;
pub const D3D11_MESSAGE_ID_CREATETEXTURE3D_INVALIDINITIALDATA: ::libc::c_uint
          =
    117;
pub const D3D11_MESSAGE_ID_CREATETEXTURE3D_INVALIDDIMENSIONS: ::libc::c_uint =
    118;
pub const D3D11_MESSAGE_ID_CREATETEXTURE3D_INVALIDMIPLEVELS: ::libc::c_uint =
    119;
pub const D3D11_MESSAGE_ID_CREATETEXTURE3D_INVALIDMISCFLAGS: ::libc::c_uint =
    120;
pub const D3D11_MESSAGE_ID_CREATETEXTURE3D_INVALIDARG_RETURN: ::libc::c_uint =
    121;
pub const D3D11_MESSAGE_ID_CREATETEXTURE3D_OUTOFMEMORY_RETURN: ::libc::c_uint
          =
    122;
pub const D3D11_MESSAGE_ID_CREATETEXTURE3D_NULLDESC: ::libc::c_uint = 123;
pub const D3D11_MESSAGE_ID_CREATETEXTURE3D_LARGEALLOCATION: ::libc::c_uint =
    124;
pub const D3D11_MESSAGE_ID_CREATESHADERRESOURCEVIEW_UNRECOGNIZEDFORMAT:
          ::libc::c_uint =
    125;
pub const D3D11_MESSAGE_ID_CREATESHADERRESOURCEVIEW_INVALIDDESC:
          ::libc::c_uint =
    126;
pub const D3D11_MESSAGE_ID_CREATESHADERRESOURCEVIEW_INVALIDFORMAT:
          ::libc::c_uint =
    127;
pub const D3D11_MESSAGE_ID_CREATESHADERRESOURCEVIEW_INVALIDDIMENSIONS:
          ::libc::c_uint =
    128;
pub const D3D11_MESSAGE_ID_CREATESHADERRESOURCEVIEW_INVALIDRESOURCE:
          ::libc::c_uint =
    129;
pub const D3D11_MESSAGE_ID_CREATESHADERRESOURCEVIEW_TOOMANYOBJECTS:
          ::libc::c_uint =
    130;
pub const D3D11_MESSAGE_ID_CREATESHADERRESOURCEVIEW_INVALIDARG_RETURN:
          ::libc::c_uint =
    131;
pub const D3D11_MESSAGE_ID_CREATESHADERRESOURCEVIEW_OUTOFMEMORY_RETURN:
          ::libc::c_uint =
    132;
pub const D3D11_MESSAGE_ID_CREATERENDERTARGETVIEW_UNRECOGNIZEDFORMAT:
          ::libc::c_uint =
    133;
pub const D3D11_MESSAGE_ID_CREATERENDERTARGETVIEW_UNSUPPORTEDFORMAT:
          ::libc::c_uint =
    134;
pub const D3D11_MESSAGE_ID_CREATERENDERTARGETVIEW_INVALIDDESC: ::libc::c_uint
          =
    135;
pub const D3D11_MESSAGE_ID_CREATERENDERTARGETVIEW_INVALIDFORMAT:
          ::libc::c_uint =
    136;
pub const D3D11_MESSAGE_ID_CREATERENDERTARGETVIEW_INVALIDDIMENSIONS:
          ::libc::c_uint =
    137;
pub const D3D11_MESSAGE_ID_CREATERENDERTARGETVIEW_INVALIDRESOURCE:
          ::libc::c_uint =
    138;
pub const D3D11_MESSAGE_ID_CREATERENDERTARGETVIEW_TOOMANYOBJECTS:
          ::libc::c_uint =
    139;
pub const D3D11_MESSAGE_ID_CREATERENDERTARGETVIEW_INVALIDARG_RETURN:
          ::libc::c_uint =
    140;
pub const D3D11_MESSAGE_ID_CREATERENDERTARGETVIEW_OUTOFMEMORY_RETURN:
          ::libc::c_uint =
    141;
pub const D3D11_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_UNRECOGNIZEDFORMAT:
          ::libc::c_uint =
    142;
pub const D3D11_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_INVALIDDESC: ::libc::c_uint
          =
    143;
pub const D3D11_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_INVALIDFORMAT:
          ::libc::c_uint =
    144;
pub const D3D11_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_INVALIDDIMENSIONS:
          ::libc::c_uint =
    145;
pub const D3D11_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_INVALIDRESOURCE:
          ::libc::c_uint =
    146;
pub const D3D11_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_TOOMANYOBJECTS:
          ::libc::c_uint =
    147;
pub const D3D11_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_INVALIDARG_RETURN:
          ::libc::c_uint =
    148;
pub const D3D11_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_OUTOFMEMORY_RETURN:
          ::libc::c_uint =
    149;
pub const D3D11_MESSAGE_ID_CREATEINPUTLAYOUT_OUTOFMEMORY: ::libc::c_uint =
    150;
pub const D3D11_MESSAGE_ID_CREATEINPUTLAYOUT_TOOMANYELEMENTS: ::libc::c_uint =
    151;
pub const D3D11_MESSAGE_ID_CREATEINPUTLAYOUT_INVALIDFORMAT: ::libc::c_uint =
    152;
pub const D3D11_MESSAGE_ID_CREATEINPUTLAYOUT_INCOMPATIBLEFORMAT:
          ::libc::c_uint =
    153;
pub const D3D11_MESSAGE_ID_CREATEINPUTLAYOUT_INVALIDSLOT: ::libc::c_uint =
    154;
pub const D3D11_MESSAGE_ID_CREATEINPUTLAYOUT_INVALIDINPUTSLOTCLASS:
          ::libc::c_uint =
    155;
pub const D3D11_MESSAGE_ID_CREATEINPUTLAYOUT_STEPRATESLOTCLASSMISMATCH:
          ::libc::c_uint =
    156;
pub const D3D11_MESSAGE_ID_CREATEINPUTLAYOUT_INVALIDSLOTCLASSCHANGE:
          ::libc::c_uint =
    157;
pub const D3D11_MESSAGE_ID_CREATEINPUTLAYOUT_INVALIDSTEPRATECHANGE:
          ::libc::c_uint =
    158;
pub const D3D11_MESSAGE_ID_CREATEINPUTLAYOUT_INVALIDALIGNMENT: ::libc::c_uint
          =
    159;
pub const D3D11_MESSAGE_ID_CREATEINPUTLAYOUT_DUPLICATESEMANTIC: ::libc::c_uint
          =
    160;
pub const D3D11_MESSAGE_ID_CREATEINPUTLAYOUT_UNPARSEABLEINPUTSIGNATURE:
          ::libc::c_uint =
    161;
pub const D3D11_MESSAGE_ID_CREATEINPUTLAYOUT_NULLSEMANTIC: ::libc::c_uint =
    162;
pub const D3D11_MESSAGE_ID_CREATEINPUTLAYOUT_MISSINGELEMENT: ::libc::c_uint =
    163;
pub const D3D11_MESSAGE_ID_CREATEINPUTLAYOUT_NULLDESC: ::libc::c_uint = 164;
pub const D3D11_MESSAGE_ID_CREATEVERTEXSHADER_OUTOFMEMORY: ::libc::c_uint =
    165;
pub const D3D11_MESSAGE_ID_CREATEVERTEXSHADER_INVALIDSHADERBYTECODE:
          ::libc::c_uint =
    166;
pub const D3D11_MESSAGE_ID_CREATEVERTEXSHADER_INVALIDSHADERTYPE:
          ::libc::c_uint =
    167;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADER_OUTOFMEMORY: ::libc::c_uint =
    168;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADER_INVALIDSHADERBYTECODE:
          ::libc::c_uint =
    169;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADER_INVALIDSHADERTYPE:
          ::libc::c_uint =
    170;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_OUTOFMEMORY:
          ::libc::c_uint =
    171;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSHADERBYTECODE:
          ::libc::c_uint =
    172;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSHADERTYPE:
          ::libc::c_uint =
    173;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDNUMENTRIES:
          ::libc::c_uint =
    174;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_OUTPUTSTREAMSTRIDEUNUSED:
          ::libc::c_uint =
    175;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_UNEXPECTEDDECL:
          ::libc::c_uint =
    176;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_EXPECTEDDECL:
          ::libc::c_uint =
    177;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_OUTPUTSLOT0EXPECTED:
          ::libc::c_uint =
    178;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDOUTPUTSLOT:
          ::libc::c_uint =
    179;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_ONLYONEELEMENTPERSLOT:
          ::libc::c_uint =
    180;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDCOMPONENTCOUNT:
          ::libc::c_uint =
    181;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSTARTCOMPONENTANDCOMPONENTCOUNT:
          ::libc::c_uint =
    182;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDGAPDEFINITION:
          ::libc::c_uint =
    183;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_REPEATEDOUTPUT:
          ::libc::c_uint =
    184;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDOUTPUTSTREAMSTRIDE:
          ::libc::c_uint =
    185;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_MISSINGSEMANTIC:
          ::libc::c_uint =
    186;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_MASKMISMATCH:
          ::libc::c_uint =
    187;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_CANTHAVEONLYGAPS:
          ::libc::c_uint =
    188;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_DECLTOOCOMPLEX:
          ::libc::c_uint =
    189;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_MISSINGOUTPUTSIGNATURE:
          ::libc::c_uint =
    190;
pub const D3D11_MESSAGE_ID_CREATEPIXELSHADER_OUTOFMEMORY: ::libc::c_uint =
    191;
pub const D3D11_MESSAGE_ID_CREATEPIXELSHADER_INVALIDSHADERBYTECODE:
          ::libc::c_uint =
    192;
pub const D3D11_MESSAGE_ID_CREATEPIXELSHADER_INVALIDSHADERTYPE: ::libc::c_uint
          =
    193;
pub const D3D11_MESSAGE_ID_CREATERASTERIZERSTATE_INVALIDFILLMODE:
          ::libc::c_uint =
    194;
pub const D3D11_MESSAGE_ID_CREATERASTERIZERSTATE_INVALIDCULLMODE:
          ::libc::c_uint =
    195;
pub const D3D11_MESSAGE_ID_CREATERASTERIZERSTATE_INVALIDDEPTHBIASCLAMP:
          ::libc::c_uint =
    196;
pub const D3D11_MESSAGE_ID_CREATERASTERIZERSTATE_INVALIDSLOPESCALEDDEPTHBIAS:
          ::libc::c_uint =
    197;
pub const D3D11_MESSAGE_ID_CREATERASTERIZERSTATE_TOOMANYOBJECTS:
          ::libc::c_uint =
    198;
pub const D3D11_MESSAGE_ID_CREATERASTERIZERSTATE_NULLDESC: ::libc::c_uint =
    199;
pub const D3D11_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDDEPTHWRITEMASK:
          ::libc::c_uint =
    200;
pub const D3D11_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDDEPTHFUNC:
          ::libc::c_uint =
    201;
pub const D3D11_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILFAILOP:
          ::libc::c_uint =
    202;
pub const D3D11_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILZFAILOP:
          ::libc::c_uint =
    203;
pub const D3D11_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILPASSOP:
          ::libc::c_uint =
    204;
pub const D3D11_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILFUNC:
          ::libc::c_uint =
    205;
pub const D3D11_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILFAILOP:
          ::libc::c_uint =
    206;
pub const D3D11_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILZFAILOP:
          ::libc::c_uint =
    207;
pub const D3D11_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILPASSOP:
          ::libc::c_uint =
    208;
pub const D3D11_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILFUNC:
          ::libc::c_uint =
    209;
pub const D3D11_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_TOOMANYOBJECTS:
          ::libc::c_uint =
    210;
pub const D3D11_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_NULLDESC: ::libc::c_uint =
    211;
pub const D3D11_MESSAGE_ID_CREATEBLENDSTATE_INVALIDSRCBLEND: ::libc::c_uint =
    212;
pub const D3D11_MESSAGE_ID_CREATEBLENDSTATE_INVALIDDESTBLEND: ::libc::c_uint =
    213;
pub const D3D11_MESSAGE_ID_CREATEBLENDSTATE_INVALIDBLENDOP: ::libc::c_uint =
    214;
pub const D3D11_MESSAGE_ID_CREATEBLENDSTATE_INVALIDSRCBLENDALPHA:
          ::libc::c_uint =
    215;
pub const D3D11_MESSAGE_ID_CREATEBLENDSTATE_INVALIDDESTBLENDALPHA:
          ::libc::c_uint =
    216;
pub const D3D11_MESSAGE_ID_CREATEBLENDSTATE_INVALIDBLENDOPALPHA:
          ::libc::c_uint =
    217;
pub const D3D11_MESSAGE_ID_CREATEBLENDSTATE_INVALIDRENDERTARGETWRITEMASK:
          ::libc::c_uint =
    218;
pub const D3D11_MESSAGE_ID_CREATEBLENDSTATE_TOOMANYOBJECTS: ::libc::c_uint =
    219;
pub const D3D11_MESSAGE_ID_CREATEBLENDSTATE_NULLDESC: ::libc::c_uint = 220;
pub const D3D11_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDFILTER: ::libc::c_uint =
    221;
pub const D3D11_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDADDRESSU: ::libc::c_uint
          =
    222;
pub const D3D11_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDADDRESSV: ::libc::c_uint
          =
    223;
pub const D3D11_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDADDRESSW: ::libc::c_uint
          =
    224;
pub const D3D11_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDMIPLODBIAS:
          ::libc::c_uint =
    225;
pub const D3D11_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDMAXANISOTROPY:
          ::libc::c_uint =
    226;
pub const D3D11_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDCOMPARISONFUNC:
          ::libc::c_uint =
    227;
pub const D3D11_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDMINLOD: ::libc::c_uint =
    228;
pub const D3D11_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDMAXLOD: ::libc::c_uint =
    229;
pub const D3D11_MESSAGE_ID_CREATESAMPLERSTATE_TOOMANYOBJECTS: ::libc::c_uint =
    230;
pub const D3D11_MESSAGE_ID_CREATESAMPLERSTATE_NULLDESC: ::libc::c_uint = 231;
pub const D3D11_MESSAGE_ID_CREATEQUERYORPREDICATE_INVALIDQUERY: ::libc::c_uint
          =
    232;
pub const D3D11_MESSAGE_ID_CREATEQUERYORPREDICATE_INVALIDMISCFLAGS:
          ::libc::c_uint =
    233;
pub const D3D11_MESSAGE_ID_CREATEQUERYORPREDICATE_UNEXPECTEDMISCFLAG:
          ::libc::c_uint =
    234;
pub const D3D11_MESSAGE_ID_CREATEQUERYORPREDICATE_NULLDESC: ::libc::c_uint =
    235;
pub const D3D11_MESSAGE_ID_DEVICE_IASETPRIMITIVETOPOLOGY_TOPOLOGY_UNRECOGNIZED:
          ::libc::c_uint =
    236;
pub const D3D11_MESSAGE_ID_DEVICE_IASETPRIMITIVETOPOLOGY_TOPOLOGY_UNDEFINED:
          ::libc::c_uint =
    237;
pub const D3D11_MESSAGE_ID_IASETVERTEXBUFFERS_INVALIDBUFFER: ::libc::c_uint =
    238;
pub const D3D11_MESSAGE_ID_DEVICE_IASETVERTEXBUFFERS_OFFSET_TOO_LARGE:
          ::libc::c_uint =
    239;
pub const D3D11_MESSAGE_ID_DEVICE_IASETVERTEXBUFFERS_BUFFERS_EMPTY:
          ::libc::c_uint =
    240;
pub const D3D11_MESSAGE_ID_IASETINDEXBUFFER_INVALIDBUFFER: ::libc::c_uint =
    241;
pub const D3D11_MESSAGE_ID_DEVICE_IASETINDEXBUFFER_FORMAT_INVALID:
          ::libc::c_uint =
    242;
pub const D3D11_MESSAGE_ID_DEVICE_IASETINDEXBUFFER_OFFSET_TOO_LARGE:
          ::libc::c_uint =
    243;
pub const D3D11_MESSAGE_ID_DEVICE_IASETINDEXBUFFER_OFFSET_UNALIGNED:
          ::libc::c_uint =
    244;
pub const D3D11_MESSAGE_ID_DEVICE_VSSETSHADERRESOURCES_VIEWS_EMPTY:
          ::libc::c_uint =
    245;
pub const D3D11_MESSAGE_ID_VSSETCONSTANTBUFFERS_INVALIDBUFFER: ::libc::c_uint
          =
    246;
pub const D3D11_MESSAGE_ID_DEVICE_VSSETCONSTANTBUFFERS_BUFFERS_EMPTY:
          ::libc::c_uint =
    247;
pub const D3D11_MESSAGE_ID_DEVICE_VSSETSAMPLERS_SAMPLERS_EMPTY: ::libc::c_uint
          =
    248;
pub const D3D11_MESSAGE_ID_DEVICE_GSSETSHADERRESOURCES_VIEWS_EMPTY:
          ::libc::c_uint =
    249;
pub const D3D11_MESSAGE_ID_GSSETCONSTANTBUFFERS_INVALIDBUFFER: ::libc::c_uint
          =
    250;
pub const D3D11_MESSAGE_ID_DEVICE_GSSETCONSTANTBUFFERS_BUFFERS_EMPTY:
          ::libc::c_uint =
    251;
pub const D3D11_MESSAGE_ID_DEVICE_GSSETSAMPLERS_SAMPLERS_EMPTY: ::libc::c_uint
          =
    252;
pub const D3D11_MESSAGE_ID_SOSETTARGETS_INVALIDBUFFER: ::libc::c_uint = 253;
pub const D3D11_MESSAGE_ID_DEVICE_SOSETTARGETS_OFFSET_UNALIGNED:
          ::libc::c_uint =
    254;
pub const D3D11_MESSAGE_ID_DEVICE_PSSETSHADERRESOURCES_VIEWS_EMPTY:
          ::libc::c_uint =
    255;
pub const D3D11_MESSAGE_ID_PSSETCONSTANTBUFFERS_INVALIDBUFFER: ::libc::c_uint
          =
    256;
pub const D3D11_MESSAGE_ID_DEVICE_PSSETCONSTANTBUFFERS_BUFFERS_EMPTY:
          ::libc::c_uint =
    257;
pub const D3D11_MESSAGE_ID_DEVICE_PSSETSAMPLERS_SAMPLERS_EMPTY: ::libc::c_uint
          =
    258;
pub const D3D11_MESSAGE_ID_DEVICE_RSSETVIEWPORTS_INVALIDVIEWPORT:
          ::libc::c_uint =
    259;
pub const D3D11_MESSAGE_ID_DEVICE_RSSETSCISSORRECTS_INVALIDSCISSOR:
          ::libc::c_uint =
    260;
pub const D3D11_MESSAGE_ID_CLEARRENDERTARGETVIEW_DENORMFLUSH: ::libc::c_uint =
    261;
pub const D3D11_MESSAGE_ID_CLEARDEPTHSTENCILVIEW_DENORMFLUSH: ::libc::c_uint =
    262;
pub const D3D11_MESSAGE_ID_CLEARDEPTHSTENCILVIEW_INVALID: ::libc::c_uint =
    263;
pub const D3D11_MESSAGE_ID_DEVICE_IAGETVERTEXBUFFERS_BUFFERS_EMPTY:
          ::libc::c_uint =
    264;
pub const D3D11_MESSAGE_ID_DEVICE_VSGETSHADERRESOURCES_VIEWS_EMPTY:
          ::libc::c_uint =
    265;
pub const D3D11_MESSAGE_ID_DEVICE_VSGETCONSTANTBUFFERS_BUFFERS_EMPTY:
          ::libc::c_uint =
    266;
pub const D3D11_MESSAGE_ID_DEVICE_VSGETSAMPLERS_SAMPLERS_EMPTY: ::libc::c_uint
          =
    267;
pub const D3D11_MESSAGE_ID_DEVICE_GSGETSHADERRESOURCES_VIEWS_EMPTY:
          ::libc::c_uint =
    268;
pub const D3D11_MESSAGE_ID_DEVICE_GSGETCONSTANTBUFFERS_BUFFERS_EMPTY:
          ::libc::c_uint =
    269;
pub const D3D11_MESSAGE_ID_DEVICE_GSGETSAMPLERS_SAMPLERS_EMPTY: ::libc::c_uint
          =
    270;
pub const D3D11_MESSAGE_ID_DEVICE_SOGETTARGETS_BUFFERS_EMPTY: ::libc::c_uint =
    271;
pub const D3D11_MESSAGE_ID_DEVICE_PSGETSHADERRESOURCES_VIEWS_EMPTY:
          ::libc::c_uint =
    272;
pub const D3D11_MESSAGE_ID_DEVICE_PSGETCONSTANTBUFFERS_BUFFERS_EMPTY:
          ::libc::c_uint =
    273;
pub const D3D11_MESSAGE_ID_DEVICE_PSGETSAMPLERS_SAMPLERS_EMPTY: ::libc::c_uint
          =
    274;
pub const D3D11_MESSAGE_ID_DEVICE_RSGETVIEWPORTS_VIEWPORTS_EMPTY:
          ::libc::c_uint =
    275;
pub const D3D11_MESSAGE_ID_DEVICE_RSGETSCISSORRECTS_RECTS_EMPTY:
          ::libc::c_uint =
    276;
pub const D3D11_MESSAGE_ID_DEVICE_GENERATEMIPS_RESOURCE_INVALID:
          ::libc::c_uint =
    277;
pub const D3D11_MESSAGE_ID_COPYSUBRESOURCEREGION_INVALIDDESTINATIONSUBRESOURCE:
          ::libc::c_uint =
    278;
pub const D3D11_MESSAGE_ID_COPYSUBRESOURCEREGION_INVALIDSOURCESUBRESOURCE:
          ::libc::c_uint =
    279;
pub const D3D11_MESSAGE_ID_COPYSUBRESOURCEREGION_INVALIDSOURCEBOX:
          ::libc::c_uint =
    280;
pub const D3D11_MESSAGE_ID_COPYSUBRESOURCEREGION_INVALIDSOURCE: ::libc::c_uint
          =
    281;
pub const D3D11_MESSAGE_ID_COPYSUBRESOURCEREGION_INVALIDDESTINATIONSTATE:
          ::libc::c_uint =
    282;
pub const D3D11_MESSAGE_ID_COPYSUBRESOURCEREGION_INVALIDSOURCESTATE:
          ::libc::c_uint =
    283;
pub const D3D11_MESSAGE_ID_COPYRESOURCE_INVALIDSOURCE: ::libc::c_uint = 284;
pub const D3D11_MESSAGE_ID_COPYRESOURCE_INVALIDDESTINATIONSTATE:
          ::libc::c_uint =
    285;
pub const D3D11_MESSAGE_ID_COPYRESOURCE_INVALIDSOURCESTATE: ::libc::c_uint =
    286;
pub const D3D11_MESSAGE_ID_UPDATESUBRESOURCE_INVALIDDESTINATIONSUBRESOURCE:
          ::libc::c_uint =
    287;
pub const D3D11_MESSAGE_ID_UPDATESUBRESOURCE_INVALIDDESTINATIONBOX:
          ::libc::c_uint =
    288;
pub const D3D11_MESSAGE_ID_UPDATESUBRESOURCE_INVALIDDESTINATIONSTATE:
          ::libc::c_uint =
    289;
pub const D3D11_MESSAGE_ID_DEVICE_RESOLVESUBRESOURCE_DESTINATION_INVALID:
          ::libc::c_uint =
    290;
pub const D3D11_MESSAGE_ID_DEVICE_RESOLVESUBRESOURCE_DESTINATION_SUBRESOURCE_INVALID:
          ::libc::c_uint =
    291;
pub const D3D11_MESSAGE_ID_DEVICE_RESOLVESUBRESOURCE_SOURCE_INVALID:
          ::libc::c_uint =
    292;
pub const D3D11_MESSAGE_ID_DEVICE_RESOLVESUBRESOURCE_SOURCE_SUBRESOURCE_INVALID:
          ::libc::c_uint =
    293;
pub const D3D11_MESSAGE_ID_DEVICE_RESOLVESUBRESOURCE_FORMAT_INVALID:
          ::libc::c_uint =
    294;
pub const D3D11_MESSAGE_ID_BUFFER_MAP_INVALIDMAPTYPE: ::libc::c_uint = 295;
pub const D3D11_MESSAGE_ID_BUFFER_MAP_INVALIDFLAGS: ::libc::c_uint = 296;
pub const D3D11_MESSAGE_ID_BUFFER_MAP_ALREADYMAPPED: ::libc::c_uint = 297;
pub const D3D11_MESSAGE_ID_BUFFER_MAP_DEVICEREMOVED_RETURN: ::libc::c_uint =
    298;
pub const D3D11_MESSAGE_ID_BUFFER_UNMAP_NOTMAPPED: ::libc::c_uint = 299;
pub const D3D11_MESSAGE_ID_TEXTURE1D_MAP_INVALIDMAPTYPE: ::libc::c_uint = 300;
pub const D3D11_MESSAGE_ID_TEXTURE1D_MAP_INVALIDSUBRESOURCE: ::libc::c_uint =
    301;
pub const D3D11_MESSAGE_ID_TEXTURE1D_MAP_INVALIDFLAGS: ::libc::c_uint = 302;
pub const D3D11_MESSAGE_ID_TEXTURE1D_MAP_ALREADYMAPPED: ::libc::c_uint = 303;
pub const D3D11_MESSAGE_ID_TEXTURE1D_MAP_DEVICEREMOVED_RETURN: ::libc::c_uint
          =
    304;
pub const D3D11_MESSAGE_ID_TEXTURE1D_UNMAP_INVALIDSUBRESOURCE: ::libc::c_uint
          =
    305;
pub const D3D11_MESSAGE_ID_TEXTURE1D_UNMAP_NOTMAPPED: ::libc::c_uint = 306;
pub const D3D11_MESSAGE_ID_TEXTURE2D_MAP_INVALIDMAPTYPE: ::libc::c_uint = 307;
pub const D3D11_MESSAGE_ID_TEXTURE2D_MAP_INVALIDSUBRESOURCE: ::libc::c_uint =
    308;
pub const D3D11_MESSAGE_ID_TEXTURE2D_MAP_INVALIDFLAGS: ::libc::c_uint = 309;
pub const D3D11_MESSAGE_ID_TEXTURE2D_MAP_ALREADYMAPPED: ::libc::c_uint = 310;
pub const D3D11_MESSAGE_ID_TEXTURE2D_MAP_DEVICEREMOVED_RETURN: ::libc::c_uint
          =
    311;
pub const D3D11_MESSAGE_ID_TEXTURE2D_UNMAP_INVALIDSUBRESOURCE: ::libc::c_uint
          =
    312;
pub const D3D11_MESSAGE_ID_TEXTURE2D_UNMAP_NOTMAPPED: ::libc::c_uint = 313;
pub const D3D11_MESSAGE_ID_TEXTURE3D_MAP_INVALIDMAPTYPE: ::libc::c_uint = 314;
pub const D3D11_MESSAGE_ID_TEXTURE3D_MAP_INVALIDSUBRESOURCE: ::libc::c_uint =
    315;
pub const D3D11_MESSAGE_ID_TEXTURE3D_MAP_INVALIDFLAGS: ::libc::c_uint = 316;
pub const D3D11_MESSAGE_ID_TEXTURE3D_MAP_ALREADYMAPPED: ::libc::c_uint = 317;
pub const D3D11_MESSAGE_ID_TEXTURE3D_MAP_DEVICEREMOVED_RETURN: ::libc::c_uint
          =
    318;
pub const D3D11_MESSAGE_ID_TEXTURE3D_UNMAP_INVALIDSUBRESOURCE: ::libc::c_uint
          =
    319;
pub const D3D11_MESSAGE_ID_TEXTURE3D_UNMAP_NOTMAPPED: ::libc::c_uint = 320;
pub const D3D11_MESSAGE_ID_CHECKFORMATSUPPORT_FORMAT_DEPRECATED:
          ::libc::c_uint =
    321;
pub const D3D11_MESSAGE_ID_CHECKMULTISAMPLEQUALITYLEVELS_FORMAT_DEPRECATED:
          ::libc::c_uint =
    322;
pub const D3D11_MESSAGE_ID_SETEXCEPTIONMODE_UNRECOGNIZEDFLAGS: ::libc::c_uint
          =
    323;
pub const D3D11_MESSAGE_ID_SETEXCEPTIONMODE_INVALIDARG_RETURN: ::libc::c_uint
          =
    324;
pub const D3D11_MESSAGE_ID_SETEXCEPTIONMODE_DEVICEREMOVED_RETURN:
          ::libc::c_uint =
    325;
pub const D3D11_MESSAGE_ID_REF_SIMULATING_INFINITELY_FAST_HARDWARE:
          ::libc::c_uint =
    326;
pub const D3D11_MESSAGE_ID_REF_THREADING_MODE: ::libc::c_uint = 327;
pub const D3D11_MESSAGE_ID_REF_UMDRIVER_EXCEPTION: ::libc::c_uint = 328;
pub const D3D11_MESSAGE_ID_REF_KMDRIVER_EXCEPTION: ::libc::c_uint = 329;
pub const D3D11_MESSAGE_ID_REF_HARDWARE_EXCEPTION: ::libc::c_uint = 330;
pub const D3D11_MESSAGE_ID_REF_ACCESSING_INDEXABLE_TEMP_OUT_OF_RANGE:
          ::libc::c_uint =
    331;
pub const D3D11_MESSAGE_ID_REF_PROBLEM_PARSING_SHADER: ::libc::c_uint = 332;
pub const D3D11_MESSAGE_ID_REF_OUT_OF_MEMORY: ::libc::c_uint = 333;
pub const D3D11_MESSAGE_ID_REF_INFO: ::libc::c_uint = 334;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_VERTEXPOS_OVERFLOW: ::libc::c_uint =
    335;
pub const D3D11_MESSAGE_ID_DEVICE_DRAWINDEXED_INDEXPOS_OVERFLOW:
          ::libc::c_uint =
    336;
pub const D3D11_MESSAGE_ID_DEVICE_DRAWINSTANCED_VERTEXPOS_OVERFLOW:
          ::libc::c_uint =
    337;
pub const D3D11_MESSAGE_ID_DEVICE_DRAWINSTANCED_INSTANCEPOS_OVERFLOW:
          ::libc::c_uint =
    338;
pub const D3D11_MESSAGE_ID_DEVICE_DRAWINDEXEDINSTANCED_INSTANCEPOS_OVERFLOW:
          ::libc::c_uint =
    339;
pub const D3D11_MESSAGE_ID_DEVICE_DRAWINDEXEDINSTANCED_INDEXPOS_OVERFLOW:
          ::libc::c_uint =
    340;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_VERTEX_SHADER_NOT_SET: ::libc::c_uint =
    341;
pub const D3D11_MESSAGE_ID_DEVICE_SHADER_LINKAGE_SEMANTICNAME_NOT_FOUND:
          ::libc::c_uint =
    342;
pub const D3D11_MESSAGE_ID_DEVICE_SHADER_LINKAGE_REGISTERINDEX: ::libc::c_uint
          =
    343;
pub const D3D11_MESSAGE_ID_DEVICE_SHADER_LINKAGE_COMPONENTTYPE: ::libc::c_uint
          =
    344;
pub const D3D11_MESSAGE_ID_DEVICE_SHADER_LINKAGE_REGISTERMASK: ::libc::c_uint
          =
    345;
pub const D3D11_MESSAGE_ID_DEVICE_SHADER_LINKAGE_SYSTEMVALUE: ::libc::c_uint =
    346;
pub const D3D11_MESSAGE_ID_DEVICE_SHADER_LINKAGE_NEVERWRITTEN_ALWAYSREADS:
          ::libc::c_uint =
    347;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_VERTEX_BUFFER_NOT_SET: ::libc::c_uint =
    348;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_INPUTLAYOUT_NOT_SET: ::libc::c_uint =
    349;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_CONSTANT_BUFFER_NOT_SET: ::libc::c_uint
          =
    350;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_CONSTANT_BUFFER_TOO_SMALL:
          ::libc::c_uint =
    351;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_SAMPLER_NOT_SET: ::libc::c_uint = 352;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_SHADERRESOURCEVIEW_NOT_SET:
          ::libc::c_uint =
    353;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_VIEW_DIMENSION_MISMATCH: ::libc::c_uint
          =
    354;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_VERTEX_BUFFER_STRIDE_TOO_SMALL:
          ::libc::c_uint =
    355;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_VERTEX_BUFFER_TOO_SMALL: ::libc::c_uint
          =
    356;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_INDEX_BUFFER_NOT_SET: ::libc::c_uint =
    357;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_INDEX_BUFFER_FORMAT_INVALID:
          ::libc::c_uint =
    358;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_INDEX_BUFFER_TOO_SMALL: ::libc::c_uint
          =
    359;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_GS_INPUT_PRIMITIVE_MISMATCH:
          ::libc::c_uint =
    360;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_RESOURCE_RETURN_TYPE_MISMATCH:
          ::libc::c_uint =
    361;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_POSITION_NOT_PRESENT: ::libc::c_uint =
    362;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_OUTPUT_STREAM_NOT_SET: ::libc::c_uint =
    363;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_BOUND_RESOURCE_MAPPED: ::libc::c_uint =
    364;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_INVALID_PRIMITIVETOPOLOGY:
          ::libc::c_uint =
    365;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_VERTEX_OFFSET_UNALIGNED: ::libc::c_uint
          =
    366;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_VERTEX_STRIDE_UNALIGNED: ::libc::c_uint
          =
    367;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_INDEX_OFFSET_UNALIGNED: ::libc::c_uint
          =
    368;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_OUTPUT_STREAM_OFFSET_UNALIGNED:
          ::libc::c_uint =
    369;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_RESOURCE_FORMAT_LD_UNSUPPORTED:
          ::libc::c_uint =
    370;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_RESOURCE_FORMAT_SAMPLE_UNSUPPORTED:
          ::libc::c_uint =
    371;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_RESOURCE_FORMAT_SAMPLE_C_UNSUPPORTED:
          ::libc::c_uint =
    372;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_RESOURCE_MULTISAMPLE_UNSUPPORTED:
          ::libc::c_uint =
    373;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_SO_TARGETS_BOUND_WITHOUT_SOURCE:
          ::libc::c_uint =
    374;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_SO_STRIDE_LARGER_THAN_BUFFER:
          ::libc::c_uint =
    375;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_OM_RENDER_TARGET_DOES_NOT_SUPPORT_BLENDING:
          ::libc::c_uint =
    376;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_OM_DUAL_SOURCE_BLENDING_CAN_ONLY_HAVE_RENDER_TARGET_0:
          ::libc::c_uint =
    377;
pub const D3D11_MESSAGE_ID_DEVICE_REMOVAL_PROCESS_AT_FAULT: ::libc::c_uint =
    378;
pub const D3D11_MESSAGE_ID_DEVICE_REMOVAL_PROCESS_POSSIBLY_AT_FAULT:
          ::libc::c_uint =
    379;
pub const D3D11_MESSAGE_ID_DEVICE_REMOVAL_PROCESS_NOT_AT_FAULT: ::libc::c_uint
          =
    380;
pub const D3D11_MESSAGE_ID_DEVICE_OPEN_SHARED_RESOURCE_INVALIDARG_RETURN:
          ::libc::c_uint =
    381;
pub const D3D11_MESSAGE_ID_DEVICE_OPEN_SHARED_RESOURCE_OUTOFMEMORY_RETURN:
          ::libc::c_uint =
    382;
pub const D3D11_MESSAGE_ID_DEVICE_OPEN_SHARED_RESOURCE_BADINTERFACE_RETURN:
          ::libc::c_uint =
    383;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_VIEWPORT_NOT_SET: ::libc::c_uint = 384;
pub const D3D11_MESSAGE_ID_CREATEINPUTLAYOUT_TRAILING_DIGIT_IN_SEMANTIC:
          ::libc::c_uint =
    385;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_TRAILING_DIGIT_IN_SEMANTIC:
          ::libc::c_uint =
    386;
pub const D3D11_MESSAGE_ID_DEVICE_RSSETVIEWPORTS_DENORMFLUSH: ::libc::c_uint =
    387;
pub const D3D11_MESSAGE_ID_OMSETRENDERTARGETS_INVALIDVIEW: ::libc::c_uint =
    388;
pub const D3D11_MESSAGE_ID_DEVICE_SETTEXTFILTERSIZE_INVALIDDIMENSIONS:
          ::libc::c_uint =
    389;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_SAMPLER_MISMATCH: ::libc::c_uint = 390;
pub const D3D11_MESSAGE_ID_CREATEINPUTLAYOUT_TYPE_MISMATCH: ::libc::c_uint =
    391;
pub const D3D11_MESSAGE_ID_BLENDSTATE_GETDESC_LEGACY: ::libc::c_uint = 392;
pub const D3D11_MESSAGE_ID_SHADERRESOURCEVIEW_GETDESC_LEGACY: ::libc::c_uint =
    393;
pub const D3D11_MESSAGE_ID_CREATEQUERY_OUTOFMEMORY_RETURN: ::libc::c_uint =
    394;
pub const D3D11_MESSAGE_ID_CREATEPREDICATE_OUTOFMEMORY_RETURN: ::libc::c_uint
          =
    395;
pub const D3D11_MESSAGE_ID_CREATECOUNTER_OUTOFRANGE_COUNTER: ::libc::c_uint =
    396;
pub const D3D11_MESSAGE_ID_CREATECOUNTER_SIMULTANEOUS_ACTIVE_COUNTERS_EXHAUSTED:
          ::libc::c_uint =
    397;
pub const D3D11_MESSAGE_ID_CREATECOUNTER_UNSUPPORTED_WELLKNOWN_COUNTER:
          ::libc::c_uint =
    398;
pub const D3D11_MESSAGE_ID_CREATECOUNTER_OUTOFMEMORY_RETURN: ::libc::c_uint =
    399;
pub const D3D11_MESSAGE_ID_CREATECOUNTER_NONEXCLUSIVE_RETURN: ::libc::c_uint =
    400;
pub const D3D11_MESSAGE_ID_CREATECOUNTER_NULLDESC: ::libc::c_uint = 401;
pub const D3D11_MESSAGE_ID_CHECKCOUNTER_OUTOFRANGE_COUNTER: ::libc::c_uint =
    402;
pub const D3D11_MESSAGE_ID_CHECKCOUNTER_UNSUPPORTED_WELLKNOWN_COUNTER:
          ::libc::c_uint =
    403;
pub const D3D11_MESSAGE_ID_SETPREDICATION_INVALID_PREDICATE_STATE:
          ::libc::c_uint =
    404;
pub const D3D11_MESSAGE_ID_QUERY_BEGIN_UNSUPPORTED: ::libc::c_uint = 405;
pub const D3D11_MESSAGE_ID_PREDICATE_BEGIN_DURING_PREDICATION: ::libc::c_uint
          =
    406;
pub const D3D11_MESSAGE_ID_QUERY_BEGIN_DUPLICATE: ::libc::c_uint = 407;
pub const D3D11_MESSAGE_ID_QUERY_BEGIN_ABANDONING_PREVIOUS_RESULTS:
          ::libc::c_uint =
    408;
pub const D3D11_MESSAGE_ID_PREDICATE_END_DURING_PREDICATION: ::libc::c_uint =
    409;
pub const D3D11_MESSAGE_ID_QUERY_END_ABANDONING_PREVIOUS_RESULTS:
          ::libc::c_uint =
    410;
pub const D3D11_MESSAGE_ID_QUERY_END_WITHOUT_BEGIN: ::libc::c_uint = 411;
pub const D3D11_MESSAGE_ID_QUERY_GETDATA_INVALID_DATASIZE: ::libc::c_uint =
    412;
pub const D3D11_MESSAGE_ID_QUERY_GETDATA_INVALID_FLAGS: ::libc::c_uint = 413;
pub const D3D11_MESSAGE_ID_QUERY_GETDATA_INVALID_CALL: ::libc::c_uint = 414;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_PS_OUTPUT_TYPE_MISMATCH: ::libc::c_uint
          =
    415;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_RESOURCE_FORMAT_GATHER_UNSUPPORTED:
          ::libc::c_uint =
    416;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_INVALID_USE_OF_CENTER_MULTISAMPLE_PATTERN:
          ::libc::c_uint =
    417;
pub const D3D11_MESSAGE_ID_DEVICE_IASETVERTEXBUFFERS_STRIDE_TOO_LARGE:
          ::libc::c_uint =
    418;
pub const D3D11_MESSAGE_ID_DEVICE_IASETVERTEXBUFFERS_INVALIDRANGE:
          ::libc::c_uint =
    419;
pub const D3D11_MESSAGE_ID_CREATEINPUTLAYOUT_EMPTY_LAYOUT: ::libc::c_uint =
    420;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_RESOURCE_SAMPLE_COUNT_MISMATCH:
          ::libc::c_uint =
    421;
pub const D3D11_MESSAGE_ID_D3D10_MESSAGES_END: ::libc::c_uint = 422;
pub const D3D11_MESSAGE_ID_D3D10L9_MESSAGES_START: ::libc::c_uint = 1048576;
pub const D3D11_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_STENCIL_NO_TWO_SIDED:
          ::libc::c_uint =
    1048577;
pub const D3D11_MESSAGE_ID_CREATERASTERIZERSTATE_DepthBiasClamp_NOT_SUPPORTED:
          ::libc::c_uint =
    1048578;
pub const D3D11_MESSAGE_ID_CREATESAMPLERSTATE_NO_COMPARISON_SUPPORT:
          ::libc::c_uint =
    1048579;
pub const D3D11_MESSAGE_ID_CREATESAMPLERSTATE_EXCESSIVE_ANISOTROPY:
          ::libc::c_uint =
    1048580;
pub const D3D11_MESSAGE_ID_CREATESAMPLERSTATE_BORDER_OUT_OF_RANGE:
          ::libc::c_uint =
    1048581;
pub const D3D11_MESSAGE_ID_VSSETSAMPLERS_NOT_SUPPORTED: ::libc::c_uint =
    1048582;
pub const D3D11_MESSAGE_ID_VSSETSAMPLERS_TOO_MANY_SAMPLERS: ::libc::c_uint =
    1048583;
pub const D3D11_MESSAGE_ID_PSSETSAMPLERS_TOO_MANY_SAMPLERS: ::libc::c_uint =
    1048584;
pub const D3D11_MESSAGE_ID_CREATERESOURCE_NO_ARRAYS: ::libc::c_uint = 1048585;
pub const D3D11_MESSAGE_ID_CREATERESOURCE_NO_VB_AND_IB_BIND: ::libc::c_uint =
    1048586;
pub const D3D11_MESSAGE_ID_CREATERESOURCE_NO_TEXTURE_1D: ::libc::c_uint =
    1048587;
pub const D3D11_MESSAGE_ID_CREATERESOURCE_DIMENSION_OUT_OF_RANGE:
          ::libc::c_uint =
    1048588;
pub const D3D11_MESSAGE_ID_CREATERESOURCE_NOT_BINDABLE_AS_SHADER_RESOURCE:
          ::libc::c_uint =
    1048589;
pub const D3D11_MESSAGE_ID_OMSETRENDERTARGETS_TOO_MANY_RENDER_TARGETS:
          ::libc::c_uint =
    1048590;
pub const D3D11_MESSAGE_ID_OMSETRENDERTARGETS_NO_DIFFERING_BIT_DEPTHS:
          ::libc::c_uint =
    1048591;
pub const D3D11_MESSAGE_ID_IASETVERTEXBUFFERS_BAD_BUFFER_INDEX: ::libc::c_uint
          =
    1048592;
pub const D3D11_MESSAGE_ID_DEVICE_RSSETVIEWPORTS_TOO_MANY_VIEWPORTS:
          ::libc::c_uint =
    1048593;
pub const D3D11_MESSAGE_ID_DEVICE_IASETPRIMITIVETOPOLOGY_ADJACENCY_UNSUPPORTED:
          ::libc::c_uint =
    1048594;
pub const D3D11_MESSAGE_ID_DEVICE_RSSETSCISSORRECTS_TOO_MANY_SCISSORS:
          ::libc::c_uint =
    1048595;
pub const D3D11_MESSAGE_ID_COPYRESOURCE_ONLY_TEXTURE_2D_WITHIN_GPU_MEMORY:
          ::libc::c_uint =
    1048596;
pub const D3D11_MESSAGE_ID_COPYRESOURCE_NO_TEXTURE_3D_READBACK: ::libc::c_uint
          =
    1048597;
pub const D3D11_MESSAGE_ID_COPYRESOURCE_NO_TEXTURE_ONLY_READBACK:
          ::libc::c_uint =
    1048598;
pub const D3D11_MESSAGE_ID_CREATEINPUTLAYOUT_UNSUPPORTED_FORMAT:
          ::libc::c_uint =
    1048599;
pub const D3D11_MESSAGE_ID_CREATEBLENDSTATE_NO_ALPHA_TO_COVERAGE:
          ::libc::c_uint =
    1048600;
pub const D3D11_MESSAGE_ID_CREATERASTERIZERSTATE_DepthClipEnable_MUST_BE_TRUE:
          ::libc::c_uint =
    1048601;
pub const D3D11_MESSAGE_ID_DRAWINDEXED_STARTINDEXLOCATION_MUST_BE_POSITIVE:
          ::libc::c_uint =
    1048602;
pub const D3D11_MESSAGE_ID_CREATESHADERRESOURCEVIEW_MUST_USE_LOWEST_LOD:
          ::libc::c_uint =
    1048603;
pub const D3D11_MESSAGE_ID_CREATESAMPLERSTATE_MINLOD_MUST_NOT_BE_FRACTIONAL:
          ::libc::c_uint =
    1048604;
pub const D3D11_MESSAGE_ID_CREATESAMPLERSTATE_MAXLOD_MUST_BE_FLT_MAX:
          ::libc::c_uint =
    1048605;
pub const D3D11_MESSAGE_ID_CREATESHADERRESOURCEVIEW_FIRSTARRAYSLICE_MUST_BE_ZERO:
          ::libc::c_uint =
    1048606;
pub const D3D11_MESSAGE_ID_CREATESHADERRESOURCEVIEW_CUBES_MUST_HAVE_6_SIDES:
          ::libc::c_uint =
    1048607;
pub const D3D11_MESSAGE_ID_CREATERESOURCE_NOT_BINDABLE_AS_RENDER_TARGET:
          ::libc::c_uint =
    1048608;
pub const D3D11_MESSAGE_ID_CREATERESOURCE_NO_DWORD_INDEX_BUFFER:
          ::libc::c_uint =
    1048609;
pub const D3D11_MESSAGE_ID_CREATERESOURCE_MSAA_PRECLUDES_SHADER_RESOURCE:
          ::libc::c_uint =
    1048610;
pub const D3D11_MESSAGE_ID_CREATERESOURCE_PRESENTATION_PRECLUDES_SHADER_RESOURCE:
          ::libc::c_uint =
    1048611;
pub const D3D11_MESSAGE_ID_CREATEBLENDSTATE_NO_INDEPENDENT_BLEND_ENABLE:
          ::libc::c_uint =
    1048612;
pub const D3D11_MESSAGE_ID_CREATEBLENDSTATE_NO_INDEPENDENT_WRITE_MASKS:
          ::libc::c_uint =
    1048613;
pub const D3D11_MESSAGE_ID_CREATERESOURCE_NO_STREAM_OUT: ::libc::c_uint =
    1048614;
pub const D3D11_MESSAGE_ID_CREATERESOURCE_ONLY_VB_IB_FOR_BUFFERS:
          ::libc::c_uint =
    1048615;
pub const D3D11_MESSAGE_ID_CREATERESOURCE_NO_AUTOGEN_FOR_VOLUMES:
          ::libc::c_uint =
    1048616;
pub const D3D11_MESSAGE_ID_CREATERESOURCE_DXGI_FORMAT_R8G8B8A8_CANNOT_BE_SHARED:
          ::libc::c_uint =
    1048617;
pub const D3D11_MESSAGE_ID_VSSHADERRESOURCES_NOT_SUPPORTED: ::libc::c_uint =
    1048618;
pub const D3D11_MESSAGE_ID_GEOMETRY_SHADER_NOT_SUPPORTED: ::libc::c_uint =
    1048619;
pub const D3D11_MESSAGE_ID_STREAM_OUT_NOT_SUPPORTED: ::libc::c_uint = 1048620;
pub const D3D11_MESSAGE_ID_TEXT_FILTER_NOT_SUPPORTED: ::libc::c_uint =
    1048621;
pub const D3D11_MESSAGE_ID_CREATEBLENDSTATE_NO_SEPARATE_ALPHA_BLEND:
          ::libc::c_uint =
    1048622;
pub const D3D11_MESSAGE_ID_CREATEBLENDSTATE_NO_MRT_BLEND: ::libc::c_uint =
    1048623;
pub const D3D11_MESSAGE_ID_CREATEBLENDSTATE_OPERATION_NOT_SUPPORTED:
          ::libc::c_uint =
    1048624;
pub const D3D11_MESSAGE_ID_CREATESAMPLERSTATE_NO_MIRRORONCE: ::libc::c_uint =
    1048625;
pub const D3D11_MESSAGE_ID_DRAWINSTANCED_NOT_SUPPORTED: ::libc::c_uint =
    1048626;
pub const D3D11_MESSAGE_ID_DRAWINDEXEDINSTANCED_NOT_SUPPORTED_BELOW_9_3:
          ::libc::c_uint =
    1048627;
pub const D3D11_MESSAGE_ID_DRAWINDEXED_POINTLIST_UNSUPPORTED: ::libc::c_uint =
    1048628;
pub const D3D11_MESSAGE_ID_SETBLENDSTATE_SAMPLE_MASK_CANNOT_BE_ZERO:
          ::libc::c_uint =
    1048629;
pub const D3D11_MESSAGE_ID_CREATERESOURCE_DIMENSION_EXCEEDS_FEATURE_LEVEL_DEFINITION:
          ::libc::c_uint =
    1048630;
pub const D3D11_MESSAGE_ID_CREATERESOURCE_ONLY_SINGLE_MIP_LEVEL_DEPTH_STENCIL_SUPPORTED:
          ::libc::c_uint =
    1048631;
pub const D3D11_MESSAGE_ID_DEVICE_RSSETSCISSORRECTS_NEGATIVESCISSOR:
          ::libc::c_uint =
    1048632;
pub const D3D11_MESSAGE_ID_SLOT_ZERO_MUST_BE_D3D10_INPUT_PER_VERTEX_DATA:
          ::libc::c_uint =
    1048633;
pub const D3D11_MESSAGE_ID_CREATERESOURCE_NON_POW_2_MIPMAP: ::libc::c_uint =
    1048634;
pub const D3D11_MESSAGE_ID_CREATESAMPLERSTATE_BORDER_NOT_SUPPORTED:
          ::libc::c_uint =
    1048635;
pub const D3D11_MESSAGE_ID_OMSETRENDERTARGETS_NO_SRGB_MRT: ::libc::c_uint =
    1048636;
pub const D3D11_MESSAGE_ID_D3D10L9_MESSAGES_END: ::libc::c_uint = 1048637;
pub const D3D11_MESSAGE_ID_D3D11_MESSAGES_START: ::libc::c_uint = 2097152;
pub const D3D11_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_INVALIDFLAGS: ::libc::c_uint
          =
    2097153;
pub const D3D11_MESSAGE_ID_CREATEVERTEXSHADER_INVALIDCLASSLINKAGE:
          ::libc::c_uint =
    2097154;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADER_INVALIDCLASSLINKAGE:
          ::libc::c_uint =
    2097155;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDNUMSTREAMS:
          ::libc::c_uint =
    2097156;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSTREAMTORASTERIZER:
          ::libc::c_uint =
    2097157;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_UNEXPECTEDSTREAMS:
          ::libc::c_uint =
    2097158;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDCLASSLINKAGE:
          ::libc::c_uint =
    2097159;
pub const D3D11_MESSAGE_ID_CREATEPIXELSHADER_INVALIDCLASSLINKAGE:
          ::libc::c_uint =
    2097160;
pub const D3D11_MESSAGE_ID_CREATEDEFERREDCONTEXT_INVALID_COMMANDLISTFLAGS:
          ::libc::c_uint =
    2097161;
pub const D3D11_MESSAGE_ID_CREATEDEFERREDCONTEXT_SINGLETHREADED:
          ::libc::c_uint =
    2097162;
pub const D3D11_MESSAGE_ID_CREATEDEFERREDCONTEXT_INVALIDARG_RETURN:
          ::libc::c_uint =
    2097163;
pub const D3D11_MESSAGE_ID_CREATEDEFERREDCONTEXT_INVALID_CALL_RETURN:
          ::libc::c_uint =
    2097164;
pub const D3D11_MESSAGE_ID_CREATEDEFERREDCONTEXT_OUTOFMEMORY_RETURN:
          ::libc::c_uint =
    2097165;
pub const D3D11_MESSAGE_ID_FINISHDISPLAYLIST_ONIMMEDIATECONTEXT:
          ::libc::c_uint =
    2097166;
pub const D3D11_MESSAGE_ID_FINISHDISPLAYLIST_OUTOFMEMORY_RETURN:
          ::libc::c_uint =
    2097167;
pub const D3D11_MESSAGE_ID_FINISHDISPLAYLIST_INVALID_CALL_RETURN:
          ::libc::c_uint =
    2097168;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSTREAM:
          ::libc::c_uint =
    2097169;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_UNEXPECTEDENTRIES:
          ::libc::c_uint =
    2097170;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_UNEXPECTEDSTRIDES:
          ::libc::c_uint =
    2097171;
pub const D3D11_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDNUMSTRIDES:
          ::libc::c_uint =
    2097172;
pub const D3D11_MESSAGE_ID_DEVICE_HSSETSHADERRESOURCES_HAZARD: ::libc::c_uint
          =
    2097173;
pub const D3D11_MESSAGE_ID_DEVICE_HSSETCONSTANTBUFFERS_HAZARD: ::libc::c_uint
          =
    2097174;
pub const D3D11_MESSAGE_ID_HSSETSHADERRESOURCES_UNBINDDELETINGOBJECT:
          ::libc::c_uint =
    2097175;
pub const D3D11_MESSAGE_ID_HSSETCONSTANTBUFFERS_UNBINDDELETINGOBJECT:
          ::libc::c_uint =
    2097176;
pub const D3D11_MESSAGE_ID_CREATEHULLSHADER_INVALIDCALL: ::libc::c_uint =
    2097177;
pub const D3D11_MESSAGE_ID_CREATEHULLSHADER_OUTOFMEMORY: ::libc::c_uint =
    2097178;
pub const D3D11_MESSAGE_ID_CREATEHULLSHADER_INVALIDSHADERBYTECODE:
          ::libc::c_uint =
    2097179;
pub const D3D11_MESSAGE_ID_CREATEHULLSHADER_INVALIDSHADERTYPE: ::libc::c_uint
          =
    2097180;
pub const D3D11_MESSAGE_ID_CREATEHULLSHADER_INVALIDCLASSLINKAGE:
          ::libc::c_uint =
    2097181;
pub const D3D11_MESSAGE_ID_DEVICE_HSSETSHADERRESOURCES_VIEWS_EMPTY:
          ::libc::c_uint =
    2097182;
pub const D3D11_MESSAGE_ID_HSSETCONSTANTBUFFERS_INVALIDBUFFER: ::libc::c_uint
          =
    2097183;
pub const D3D11_MESSAGE_ID_DEVICE_HSSETCONSTANTBUFFERS_BUFFERS_EMPTY:
          ::libc::c_uint =
    2097184;
pub const D3D11_MESSAGE_ID_DEVICE_HSSETSAMPLERS_SAMPLERS_EMPTY: ::libc::c_uint
          =
    2097185;
pub const D3D11_MESSAGE_ID_DEVICE_HSGETSHADERRESOURCES_VIEWS_EMPTY:
          ::libc::c_uint =
    2097186;
pub const D3D11_MESSAGE_ID_DEVICE_HSGETCONSTANTBUFFERS_BUFFERS_EMPTY:
          ::libc::c_uint =
    2097187;
pub const D3D11_MESSAGE_ID_DEVICE_HSGETSAMPLERS_SAMPLERS_EMPTY: ::libc::c_uint
          =
    2097188;
pub const D3D11_MESSAGE_ID_DEVICE_DSSETSHADERRESOURCES_HAZARD: ::libc::c_uint
          =
    2097189;
pub const D3D11_MESSAGE_ID_DEVICE_DSSETCONSTANTBUFFERS_HAZARD: ::libc::c_uint
          =
    2097190;
pub const D3D11_MESSAGE_ID_DSSETSHADERRESOURCES_UNBINDDELETINGOBJECT:
          ::libc::c_uint =
    2097191;
pub const D3D11_MESSAGE_ID_DSSETCONSTANTBUFFERS_UNBINDDELETINGOBJECT:
          ::libc::c_uint =
    2097192;
pub const D3D11_MESSAGE_ID_CREATEDOMAINSHADER_INVALIDCALL: ::libc::c_uint =
    2097193;
pub const D3D11_MESSAGE_ID_CREATEDOMAINSHADER_OUTOFMEMORY: ::libc::c_uint =
    2097194;
pub const D3D11_MESSAGE_ID_CREATEDOMAINSHADER_INVALIDSHADERBYTECODE:
          ::libc::c_uint =
    2097195;
pub const D3D11_MESSAGE_ID_CREATEDOMAINSHADER_INVALIDSHADERTYPE:
          ::libc::c_uint =
    2097196;
pub const D3D11_MESSAGE_ID_CREATEDOMAINSHADER_INVALIDCLASSLINKAGE:
          ::libc::c_uint =
    2097197;
pub const D3D11_MESSAGE_ID_DEVICE_DSSETSHADERRESOURCES_VIEWS_EMPTY:
          ::libc::c_uint =
    2097198;
pub const D3D11_MESSAGE_ID_DSSETCONSTANTBUFFERS_INVALIDBUFFER: ::libc::c_uint
          =
    2097199;
pub const D3D11_MESSAGE_ID_DEVICE_DSSETCONSTANTBUFFERS_BUFFERS_EMPTY:
          ::libc::c_uint =
    2097200;
pub const D3D11_MESSAGE_ID_DEVICE_DSSETSAMPLERS_SAMPLERS_EMPTY: ::libc::c_uint
          =
    2097201;
pub const D3D11_MESSAGE_ID_DEVICE_DSGETSHADERRESOURCES_VIEWS_EMPTY:
          ::libc::c_uint =
    2097202;
pub const D3D11_MESSAGE_ID_DEVICE_DSGETCONSTANTBUFFERS_BUFFERS_EMPTY:
          ::libc::c_uint =
    2097203;
pub const D3D11_MESSAGE_ID_DEVICE_DSGETSAMPLERS_SAMPLERS_EMPTY: ::libc::c_uint
          =
    2097204;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_HS_XOR_DS_MISMATCH: ::libc::c_uint =
    2097205;
pub const D3D11_MESSAGE_ID_DEFERRED_CONTEXT_REMOVAL_PROCESS_AT_FAULT:
          ::libc::c_uint =
    2097206;
pub const D3D11_MESSAGE_ID_DEVICE_DRAWINDIRECT_INVALID_ARG_BUFFER:
          ::libc::c_uint =
    2097207;
pub const D3D11_MESSAGE_ID_DEVICE_DRAWINDIRECT_OFFSET_UNALIGNED:
          ::libc::c_uint =
    2097208;
pub const D3D11_MESSAGE_ID_DEVICE_DRAWINDIRECT_OFFSET_OVERFLOW: ::libc::c_uint
          =
    2097209;
pub const D3D11_MESSAGE_ID_RESOURCE_MAP_INVALIDMAPTYPE: ::libc::c_uint =
    2097210;
pub const D3D11_MESSAGE_ID_RESOURCE_MAP_INVALIDSUBRESOURCE: ::libc::c_uint =
    2097211;
pub const D3D11_MESSAGE_ID_RESOURCE_MAP_INVALIDFLAGS: ::libc::c_uint =
    2097212;
pub const D3D11_MESSAGE_ID_RESOURCE_MAP_ALREADYMAPPED: ::libc::c_uint =
    2097213;
pub const D3D11_MESSAGE_ID_RESOURCE_MAP_DEVICEREMOVED_RETURN: ::libc::c_uint =
    2097214;
pub const D3D11_MESSAGE_ID_RESOURCE_MAP_OUTOFMEMORY_RETURN: ::libc::c_uint =
    2097215;
pub const D3D11_MESSAGE_ID_RESOURCE_MAP_WITHOUT_INITIAL_DISCARD:
          ::libc::c_uint =
    2097216;
pub const D3D11_MESSAGE_ID_RESOURCE_UNMAP_INVALIDSUBRESOURCE: ::libc::c_uint =
    2097217;
pub const D3D11_MESSAGE_ID_RESOURCE_UNMAP_NOTMAPPED: ::libc::c_uint = 2097218;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_RASTERIZING_CONTROL_POINTS:
          ::libc::c_uint =
    2097219;
pub const D3D11_MESSAGE_ID_DEVICE_IASETPRIMITIVETOPOLOGY_TOPOLOGY_UNSUPPORTED:
          ::libc::c_uint =
    2097220;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_HS_DS_SIGNATURE_MISMATCH:
          ::libc::c_uint =
    2097221;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_HULL_SHADER_INPUT_TOPOLOGY_MISMATCH:
          ::libc::c_uint =
    2097222;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_HS_DS_CONTROL_POINT_COUNT_MISMATCH:
          ::libc::c_uint =
    2097223;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_HS_DS_TESSELLATOR_DOMAIN_MISMATCH:
          ::libc::c_uint =
    2097224;
pub const D3D11_MESSAGE_ID_CREATE_CONTEXT: ::libc::c_uint = 2097225;
pub const D3D11_MESSAGE_ID_LIVE_CONTEXT: ::libc::c_uint = 2097226;
pub const D3D11_MESSAGE_ID_DESTROY_CONTEXT: ::libc::c_uint = 2097227;
pub const D3D11_MESSAGE_ID_CREATE_BUFFER: ::libc::c_uint = 2097228;
pub const D3D11_MESSAGE_ID_LIVE_BUFFER: ::libc::c_uint = 2097229;
pub const D3D11_MESSAGE_ID_DESTROY_BUFFER: ::libc::c_uint = 2097230;
pub const D3D11_MESSAGE_ID_CREATE_TEXTURE1D: ::libc::c_uint = 2097231;
pub const D3D11_MESSAGE_ID_LIVE_TEXTURE1D: ::libc::c_uint = 2097232;
pub const D3D11_MESSAGE_ID_DESTROY_TEXTURE1D: ::libc::c_uint = 2097233;
pub const D3D11_MESSAGE_ID_CREATE_TEXTURE2D: ::libc::c_uint = 2097234;
pub const D3D11_MESSAGE_ID_LIVE_TEXTURE2D: ::libc::c_uint = 2097235;
pub const D3D11_MESSAGE_ID_DESTROY_TEXTURE2D: ::libc::c_uint = 2097236;
pub const D3D11_MESSAGE_ID_CREATE_TEXTURE3D: ::libc::c_uint = 2097237;
pub const D3D11_MESSAGE_ID_LIVE_TEXTURE3D: ::libc::c_uint = 2097238;
pub const D3D11_MESSAGE_ID_DESTROY_TEXTURE3D: ::libc::c_uint = 2097239;
pub const D3D11_MESSAGE_ID_CREATE_SHADERRESOURCEVIEW: ::libc::c_uint =
    2097240;
pub const D3D11_MESSAGE_ID_LIVE_SHADERRESOURCEVIEW: ::libc::c_uint = 2097241;
pub const D3D11_MESSAGE_ID_DESTROY_SHADERRESOURCEVIEW: ::libc::c_uint =
    2097242;
pub const D3D11_MESSAGE_ID_CREATE_RENDERTARGETVIEW: ::libc::c_uint = 2097243;
pub const D3D11_MESSAGE_ID_LIVE_RENDERTARGETVIEW: ::libc::c_uint = 2097244;
pub const D3D11_MESSAGE_ID_DESTROY_RENDERTARGETVIEW: ::libc::c_uint = 2097245;
pub const D3D11_MESSAGE_ID_CREATE_DEPTHSTENCILVIEW: ::libc::c_uint = 2097246;
pub const D3D11_MESSAGE_ID_LIVE_DEPTHSTENCILVIEW: ::libc::c_uint = 2097247;
pub const D3D11_MESSAGE_ID_DESTROY_DEPTHSTENCILVIEW: ::libc::c_uint = 2097248;
pub const D3D11_MESSAGE_ID_CREATE_VERTEXSHADER: ::libc::c_uint = 2097249;
pub const D3D11_MESSAGE_ID_LIVE_VERTEXSHADER: ::libc::c_uint = 2097250;
pub const D3D11_MESSAGE_ID_DESTROY_VERTEXSHADER: ::libc::c_uint = 2097251;
pub const D3D11_MESSAGE_ID_CREATE_HULLSHADER: ::libc::c_uint = 2097252;
pub const D3D11_MESSAGE_ID_LIVE_HULLSHADER: ::libc::c_uint = 2097253;
pub const D3D11_MESSAGE_ID_DESTROY_HULLSHADER: ::libc::c_uint = 2097254;
pub const D3D11_MESSAGE_ID_CREATE_DOMAINSHADER: ::libc::c_uint = 2097255;
pub const D3D11_MESSAGE_ID_LIVE_DOMAINSHADER: ::libc::c_uint = 2097256;
pub const D3D11_MESSAGE_ID_DESTROY_DOMAINSHADER: ::libc::c_uint = 2097257;
pub const D3D11_MESSAGE_ID_CREATE_GEOMETRYSHADER: ::libc::c_uint = 2097258;
pub const D3D11_MESSAGE_ID_LIVE_GEOMETRYSHADER: ::libc::c_uint = 2097259;
pub const D3D11_MESSAGE_ID_DESTROY_GEOMETRYSHADER: ::libc::c_uint = 2097260;
pub const D3D11_MESSAGE_ID_CREATE_PIXELSHADER: ::libc::c_uint = 2097261;
pub const D3D11_MESSAGE_ID_LIVE_PIXELSHADER: ::libc::c_uint = 2097262;
pub const D3D11_MESSAGE_ID_DESTROY_PIXELSHADER: ::libc::c_uint = 2097263;
pub const D3D11_MESSAGE_ID_CREATE_INPUTLAYOUT: ::libc::c_uint = 2097264;
pub const D3D11_MESSAGE_ID_LIVE_INPUTLAYOUT: ::libc::c_uint = 2097265;
pub const D3D11_MESSAGE_ID_DESTROY_INPUTLAYOUT: ::libc::c_uint = 2097266;
pub const D3D11_MESSAGE_ID_CREATE_SAMPLER: ::libc::c_uint = 2097267;
pub const D3D11_MESSAGE_ID_LIVE_SAMPLER: ::libc::c_uint = 2097268;
pub const D3D11_MESSAGE_ID_DESTROY_SAMPLER: ::libc::c_uint = 2097269;
pub const D3D11_MESSAGE_ID_CREATE_BLENDSTATE: ::libc::c_uint = 2097270;
pub const D3D11_MESSAGE_ID_LIVE_BLENDSTATE: ::libc::c_uint = 2097271;
pub const D3D11_MESSAGE_ID_DESTROY_BLENDSTATE: ::libc::c_uint = 2097272;
pub const D3D11_MESSAGE_ID_CREATE_DEPTHSTENCILSTATE: ::libc::c_uint = 2097273;
pub const D3D11_MESSAGE_ID_LIVE_DEPTHSTENCILSTATE: ::libc::c_uint = 2097274;
pub const D3D11_MESSAGE_ID_DESTROY_DEPTHSTENCILSTATE: ::libc::c_uint =
    2097275;
pub const D3D11_MESSAGE_ID_CREATE_RASTERIZERSTATE: ::libc::c_uint = 2097276;
pub const D3D11_MESSAGE_ID_LIVE_RASTERIZERSTATE: ::libc::c_uint = 2097277;
pub const D3D11_MESSAGE_ID_DESTROY_RASTERIZERSTATE: ::libc::c_uint = 2097278;
pub const D3D11_MESSAGE_ID_CREATE_QUERY: ::libc::c_uint = 2097279;
pub const D3D11_MESSAGE_ID_LIVE_QUERY: ::libc::c_uint = 2097280;
pub const D3D11_MESSAGE_ID_DESTROY_QUERY: ::libc::c_uint = 2097281;
pub const D3D11_MESSAGE_ID_CREATE_PREDICATE: ::libc::c_uint = 2097282;
pub const D3D11_MESSAGE_ID_LIVE_PREDICATE: ::libc::c_uint = 2097283;
pub const D3D11_MESSAGE_ID_DESTROY_PREDICATE: ::libc::c_uint = 2097284;
pub const D3D11_MESSAGE_ID_CREATE_COUNTER: ::libc::c_uint = 2097285;
pub const D3D11_MESSAGE_ID_LIVE_COUNTER: ::libc::c_uint = 2097286;
pub const D3D11_MESSAGE_ID_DESTROY_COUNTER: ::libc::c_uint = 2097287;
pub const D3D11_MESSAGE_ID_CREATE_COMMANDLIST: ::libc::c_uint = 2097288;
pub const D3D11_MESSAGE_ID_LIVE_COMMANDLIST: ::libc::c_uint = 2097289;
pub const D3D11_MESSAGE_ID_DESTROY_COMMANDLIST: ::libc::c_uint = 2097290;
pub const D3D11_MESSAGE_ID_CREATE_CLASSINSTANCE: ::libc::c_uint = 2097291;
pub const D3D11_MESSAGE_ID_LIVE_CLASSINSTANCE: ::libc::c_uint = 2097292;
pub const D3D11_MESSAGE_ID_DESTROY_CLASSINSTANCE: ::libc::c_uint = 2097293;
pub const D3D11_MESSAGE_ID_CREATE_CLASSLINKAGE: ::libc::c_uint = 2097294;
pub const D3D11_MESSAGE_ID_LIVE_CLASSLINKAGE: ::libc::c_uint = 2097295;
pub const D3D11_MESSAGE_ID_DESTROY_CLASSLINKAGE: ::libc::c_uint = 2097296;
pub const D3D11_MESSAGE_ID_LIVE_DEVICE: ::libc::c_uint = 2097297;
pub const D3D11_MESSAGE_ID_LIVE_OBJECT_SUMMARY: ::libc::c_uint = 2097298;
pub const D3D11_MESSAGE_ID_CREATE_COMPUTESHADER: ::libc::c_uint = 2097299;
pub const D3D11_MESSAGE_ID_LIVE_COMPUTESHADER: ::libc::c_uint = 2097300;
pub const D3D11_MESSAGE_ID_DESTROY_COMPUTESHADER: ::libc::c_uint = 2097301;
pub const D3D11_MESSAGE_ID_CREATE_UNORDEREDACCESSVIEW: ::libc::c_uint =
    2097302;
pub const D3D11_MESSAGE_ID_LIVE_UNORDEREDACCESSVIEW: ::libc::c_uint = 2097303;
pub const D3D11_MESSAGE_ID_DESTROY_UNORDEREDACCESSVIEW: ::libc::c_uint =
    2097304;
pub const D3D11_MESSAGE_ID_DEVICE_SETSHADER_INTERFACES_FEATURELEVEL:
          ::libc::c_uint =
    2097305;
pub const D3D11_MESSAGE_ID_DEVICE_SETSHADER_INTERFACE_COUNT_MISMATCH:
          ::libc::c_uint =
    2097306;
pub const D3D11_MESSAGE_ID_DEVICE_SETSHADER_INVALID_INSTANCE: ::libc::c_uint =
    2097307;
pub const D3D11_MESSAGE_ID_DEVICE_SETSHADER_INVALID_INSTANCE_INDEX:
          ::libc::c_uint =
    2097308;
pub const D3D11_MESSAGE_ID_DEVICE_SETSHADER_INVALID_INSTANCE_TYPE:
          ::libc::c_uint =
    2097309;
pub const D3D11_MESSAGE_ID_DEVICE_SETSHADER_INVALID_INSTANCE_DATA:
          ::libc::c_uint =
    2097310;
pub const D3D11_MESSAGE_ID_DEVICE_SETSHADER_UNBOUND_INSTANCE_DATA:
          ::libc::c_uint =
    2097311;
pub const D3D11_MESSAGE_ID_DEVICE_SETSHADER_INSTANCE_DATA_BINDINGS:
          ::libc::c_uint =
    2097312;
pub const D3D11_MESSAGE_ID_DEVICE_CREATESHADER_CLASSLINKAGE_FULL:
          ::libc::c_uint =
    2097313;
pub const D3D11_MESSAGE_ID_DEVICE_CHECKFEATURESUPPORT_UNRECOGNIZED_FEATURE:
          ::libc::c_uint =
    2097314;
pub const D3D11_MESSAGE_ID_DEVICE_CHECKFEATURESUPPORT_MISMATCHED_DATA_SIZE:
          ::libc::c_uint =
    2097315;
pub const D3D11_MESSAGE_ID_DEVICE_CHECKFEATURESUPPORT_INVALIDARG_RETURN:
          ::libc::c_uint =
    2097316;
pub const D3D11_MESSAGE_ID_DEVICE_CSSETSHADERRESOURCES_HAZARD: ::libc::c_uint
          =
    2097317;
pub const D3D11_MESSAGE_ID_DEVICE_CSSETCONSTANTBUFFERS_HAZARD: ::libc::c_uint
          =
    2097318;
pub const D3D11_MESSAGE_ID_CSSETSHADERRESOURCES_UNBINDDELETINGOBJECT:
          ::libc::c_uint =
    2097319;
pub const D3D11_MESSAGE_ID_CSSETCONSTANTBUFFERS_UNBINDDELETINGOBJECT:
          ::libc::c_uint =
    2097320;
pub const D3D11_MESSAGE_ID_CREATECOMPUTESHADER_INVALIDCALL: ::libc::c_uint =
    2097321;
pub const D3D11_MESSAGE_ID_CREATECOMPUTESHADER_OUTOFMEMORY: ::libc::c_uint =
    2097322;
pub const D3D11_MESSAGE_ID_CREATECOMPUTESHADER_INVALIDSHADERBYTECODE:
          ::libc::c_uint =
    2097323;
pub const D3D11_MESSAGE_ID_CREATECOMPUTESHADER_INVALIDSHADERTYPE:
          ::libc::c_uint =
    2097324;
pub const D3D11_MESSAGE_ID_CREATECOMPUTESHADER_INVALIDCLASSLINKAGE:
          ::libc::c_uint =
    2097325;
pub const D3D11_MESSAGE_ID_DEVICE_CSSETSHADERRESOURCES_VIEWS_EMPTY:
          ::libc::c_uint =
    2097326;
pub const D3D11_MESSAGE_ID_CSSETCONSTANTBUFFERS_INVALIDBUFFER: ::libc::c_uint
          =
    2097327;
pub const D3D11_MESSAGE_ID_DEVICE_CSSETCONSTANTBUFFERS_BUFFERS_EMPTY:
          ::libc::c_uint =
    2097328;
pub const D3D11_MESSAGE_ID_DEVICE_CSSETSAMPLERS_SAMPLERS_EMPTY: ::libc::c_uint
          =
    2097329;
pub const D3D11_MESSAGE_ID_DEVICE_CSGETSHADERRESOURCES_VIEWS_EMPTY:
          ::libc::c_uint =
    2097330;
pub const D3D11_MESSAGE_ID_DEVICE_CSGETCONSTANTBUFFERS_BUFFERS_EMPTY:
          ::libc::c_uint =
    2097331;
pub const D3D11_MESSAGE_ID_DEVICE_CSGETSAMPLERS_SAMPLERS_EMPTY: ::libc::c_uint
          =
    2097332;
pub const D3D11_MESSAGE_ID_DEVICE_CREATEVERTEXSHADER_DOUBLEFLOATOPSNOTSUPPORTED:
          ::libc::c_uint =
    2097333;
pub const D3D11_MESSAGE_ID_DEVICE_CREATEHULLSHADER_DOUBLEFLOATOPSNOTSUPPORTED:
          ::libc::c_uint =
    2097334;
pub const D3D11_MESSAGE_ID_DEVICE_CREATEDOMAINSHADER_DOUBLEFLOATOPSNOTSUPPORTED:
          ::libc::c_uint =
    2097335;
pub const D3D11_MESSAGE_ID_DEVICE_CREATEGEOMETRYSHADER_DOUBLEFLOATOPSNOTSUPPORTED:
          ::libc::c_uint =
    2097336;
pub const D3D11_MESSAGE_ID_DEVICE_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_DOUBLEFLOATOPSNOTSUPPORTED:
          ::libc::c_uint =
    2097337;
pub const D3D11_MESSAGE_ID_DEVICE_CREATEPIXELSHADER_DOUBLEFLOATOPSNOTSUPPORTED:
          ::libc::c_uint =
    2097338;
pub const D3D11_MESSAGE_ID_DEVICE_CREATECOMPUTESHADER_DOUBLEFLOATOPSNOTSUPPORTED:
          ::libc::c_uint =
    2097339;
pub const D3D11_MESSAGE_ID_CREATEBUFFER_INVALIDSTRUCTURESTRIDE: ::libc::c_uint
          =
    2097340;
pub const D3D11_MESSAGE_ID_CREATESHADERRESOURCEVIEW_INVALIDFLAGS:
          ::libc::c_uint =
    2097341;
pub const D3D11_MESSAGE_ID_CREATEUNORDEREDACCESSVIEW_INVALIDRESOURCE:
          ::libc::c_uint =
    2097342;
pub const D3D11_MESSAGE_ID_CREATEUNORDEREDACCESSVIEW_INVALIDDESC:
          ::libc::c_uint =
    2097343;
pub const D3D11_MESSAGE_ID_CREATEUNORDEREDACCESSVIEW_INVALIDFORMAT:
          ::libc::c_uint =
    2097344;
pub const D3D11_MESSAGE_ID_CREATEUNORDEREDACCESSVIEW_INVALIDDIMENSIONS:
          ::libc::c_uint =
    2097345;
pub const D3D11_MESSAGE_ID_CREATEUNORDEREDACCESSVIEW_UNRECOGNIZEDFORMAT:
          ::libc::c_uint =
    2097346;
pub const D3D11_MESSAGE_ID_DEVICE_OMSETRENDERTARGETSANDUNORDEREDACCESSVIEWS_HAZARD:
          ::libc::c_uint =
    2097347;
pub const D3D11_MESSAGE_ID_DEVICE_OMSETRENDERTARGETSANDUNORDEREDACCESSVIEWS_OVERLAPPING_OLD_SLOTS:
          ::libc::c_uint =
    2097348;
pub const D3D11_MESSAGE_ID_DEVICE_OMSETRENDERTARGETSANDUNORDEREDACCESSVIEWS_NO_OP:
          ::libc::c_uint =
    2097349;
pub const D3D11_MESSAGE_ID_CSSETUNORDEREDACCESSVIEWS_UNBINDDELETINGOBJECT:
          ::libc::c_uint =
    2097350;
pub const D3D11_MESSAGE_ID_PSSETUNORDEREDACCESSVIEWS_UNBINDDELETINGOBJECT:
          ::libc::c_uint =
    2097351;
pub const D3D11_MESSAGE_ID_CREATEUNORDEREDACCESSVIEW_INVALIDARG_RETURN:
          ::libc::c_uint =
    2097352;
pub const D3D11_MESSAGE_ID_CREATEUNORDEREDACCESSVIEW_OUTOFMEMORY_RETURN:
          ::libc::c_uint =
    2097353;
pub const D3D11_MESSAGE_ID_CREATEUNORDEREDACCESSVIEW_TOOMANYOBJECTS:
          ::libc::c_uint =
    2097354;
pub const D3D11_MESSAGE_ID_DEVICE_CSSETUNORDEREDACCESSVIEWS_HAZARD:
          ::libc::c_uint =
    2097355;
pub const D3D11_MESSAGE_ID_CLEARUNORDEREDACCESSVIEW_DENORMFLUSH:
          ::libc::c_uint =
    2097356;
pub const D3D11_MESSAGE_ID_DEVICE_CSSETUNORDEREDACCESSS_VIEWS_EMPTY:
          ::libc::c_uint =
    2097357;
pub const D3D11_MESSAGE_ID_DEVICE_CSGETUNORDEREDACCESSS_VIEWS_EMPTY:
          ::libc::c_uint =
    2097358;
pub const D3D11_MESSAGE_ID_CREATEUNORDEREDACCESSVIEW_INVALIDFLAGS:
          ::libc::c_uint =
    2097359;
pub const D3D11_MESSAGE_ID_CREATESHADERRESESOURCEVIEW_TOOMANYOBJECTS:
          ::libc::c_uint =
    2097360;
pub const D3D11_MESSAGE_ID_DEVICE_DISPATCHINDIRECT_INVALID_ARG_BUFFER:
          ::libc::c_uint =
    2097361;
pub const D3D11_MESSAGE_ID_DEVICE_DISPATCHINDIRECT_OFFSET_UNALIGNED:
          ::libc::c_uint =
    2097362;
pub const D3D11_MESSAGE_ID_DEVICE_DISPATCHINDIRECT_OFFSET_OVERFLOW:
          ::libc::c_uint =
    2097363;
pub const D3D11_MESSAGE_ID_DEVICE_SETRESOURCEMINLOD_INVALIDCONTEXT:
          ::libc::c_uint =
    2097364;
pub const D3D11_MESSAGE_ID_DEVICE_SETRESOURCEMINLOD_INVALIDRESOURCE:
          ::libc::c_uint =
    2097365;
pub const D3D11_MESSAGE_ID_DEVICE_SETRESOURCEMINLOD_INVALIDMINLOD:
          ::libc::c_uint =
    2097366;
pub const D3D11_MESSAGE_ID_DEVICE_GETRESOURCEMINLOD_INVALIDCONTEXT:
          ::libc::c_uint =
    2097367;
pub const D3D11_MESSAGE_ID_DEVICE_GETRESOURCEMINLOD_INVALIDRESOURCE:
          ::libc::c_uint =
    2097368;
pub const D3D11_MESSAGE_ID_OMSETDEPTHSTENCIL_UNBINDDELETINGOBJECT:
          ::libc::c_uint =
    2097369;
pub const D3D11_MESSAGE_ID_CLEARDEPTHSTENCILVIEW_DEPTH_READONLY:
          ::libc::c_uint =
    2097370;
pub const D3D11_MESSAGE_ID_CLEARDEPTHSTENCILVIEW_STENCIL_READONLY:
          ::libc::c_uint =
    2097371;
pub const D3D11_MESSAGE_ID_CHECKFEATURESUPPORT_FORMAT_DEPRECATED:
          ::libc::c_uint =
    2097372;
pub const D3D11_MESSAGE_ID_DEVICE_UNORDEREDACCESSVIEW_RETURN_TYPE_MISMATCH:
          ::libc::c_uint =
    2097373;
pub const D3D11_MESSAGE_ID_DEVICE_UNORDEREDACCESSVIEW_NOT_SET: ::libc::c_uint
          =
    2097374;
pub const D3D11_MESSAGE_ID_DEVICE_DRAW_UNORDEREDACCESSVIEW_RENDERTARGETVIEW_OVERLAP:
          ::libc::c_uint =
    2097375;
pub const D3D11_MESSAGE_ID_DEVICE_UNORDEREDACCESSVIEW_DIMENSION_MISMATCH:
          ::libc::c_uint =
    2097376;
pub const D3D11_MESSAGE_ID_DEVICE_UNORDEREDACCESSVIEW_APPEND_UNSUPPORTED:
          ::libc::c_uint =
    2097377;
pub const D3D11_MESSAGE_ID_DEVICE_UNORDEREDACCESSVIEW_ATOMICS_UNSUPPORTED:
          ::libc::c_uint =
    2097378;
pub const D3D11_MESSAGE_ID_DEVICE_UNORDEREDACCESSVIEW_STRUCTURE_STRIDE_MISMATCH:
          ::libc::c_uint =
    2097379;
pub const D3D11_MESSAGE_ID_DEVICE_UNORDEREDACCESSVIEW_BUFFER_TYPE_MISMATCH:
          ::libc::c_uint =
    2097380;
pub const D3D11_MESSAGE_ID_DEVICE_UNORDEREDACCESSVIEW_RAW_UNSUPPORTED:
          ::libc::c_uint =
    2097381;
pub const D3D11_MESSAGE_ID_DEVICE_UNORDEREDACCESSVIEW_FORMAT_LD_UNSUPPORTED:
          ::libc::c_uint =
    2097382;
pub const D3D11_MESSAGE_ID_DEVICE_UNORDEREDACCESSVIEW_FORMAT_STORE_UNSUPPORTED:
          ::libc::c_uint =
    2097383;
pub const D3D11_MESSAGE_ID_DEVICE_UNORDEREDACCESSVIEW_ATOMIC_ADD_UNSUPPORTED:
          ::libc::c_uint =
    2097384;
pub const D3D11_MESSAGE_ID_DEVICE_UNORDEREDACCESSVIEW_ATOMIC_BITWISE_OPS_UNSUPPORTED:
          ::libc::c_uint =
    2097385;
pub const D3D11_MESSAGE_ID_DEVICE_UNORDEREDACCESSVIEW_ATOMIC_CMPSTORE_CMPEXCHANGE_UNSUPPORTED:
          ::libc::c_uint =
    2097386;
pub const D3D11_MESSAGE_ID_DEVICE_UNORDEREDACCESSVIEW_ATOMIC_EXCHANGE_UNSUPPORTED:
          ::libc::c_uint =
    2097387;
pub const D3D11_MESSAGE_ID_DEVICE_UNORDEREDACCESSVIEW_ATOMIC_SIGNED_MINMAX_UNSUPPORTED:
          ::libc::c_uint =
    2097388;
pub const D3D11_MESSAGE_ID_DEVICE_UNORDEREDACCESSVIEW_ATOMIC_UNSIGNED_MINMAX_UNSUPPORTED:
          ::libc::c_uint =
    2097389;
pub const D3D11_MESSAGE_ID_DEVICE_DISPATCH_BOUND_RESOURCE_MAPPED:
          ::libc::c_uint =
    2097390;
pub const D3D11_MESSAGE_ID_DEVICE_DISPATCH_THREADGROUPCOUNT_OVERFLOW:
          ::libc::c_uint =
    2097391;
pub const D3D11_MESSAGE_ID_DEVICE_DISPATCH_THREADGROUPCOUNT_ZERO:
          ::libc::c_uint =
    2097392;
pub const D3D11_MESSAGE_ID_DEVICE_SHADERRESOURCEVIEW_STRUCTURE_STRIDE_MISMATCH:
          ::libc::c_uint =
    2097393;
pub const D3D11_MESSAGE_ID_DEVICE_SHADERRESOURCEVIEW_BUFFER_TYPE_MISMATCH:
          ::libc::c_uint =
    2097394;
pub const D3D11_MESSAGE_ID_DEVICE_SHADERRESOURCEVIEW_RAW_UNSUPPORTED:
          ::libc::c_uint =
    2097395;
pub const D3D11_MESSAGE_ID_DEVICE_DISPATCH_UNSUPPORTED: ::libc::c_uint =
    2097396;
pub const D3D11_MESSAGE_ID_DEVICE_DISPATCHINDIRECT_UNSUPPORTED: ::libc::c_uint
          =
    2097397;
pub const D3D11_MESSAGE_ID_COPYSTRUCTURECOUNT_INVALIDOFFSET: ::libc::c_uint =
    2097398;
pub const D3D11_MESSAGE_ID_COPYSTRUCTURECOUNT_LARGEOFFSET: ::libc::c_uint =
    2097399;
pub const D3D11_MESSAGE_ID_COPYSTRUCTURECOUNT_INVALIDDESTINATIONSTATE:
          ::libc::c_uint =
    2097400;
pub const D3D11_MESSAGE_ID_COPYSTRUCTURECOUNT_INVALIDSOURCESTATE:
          ::libc::c_uint =
    2097401;
pub const D3D11_MESSAGE_ID_CHECKFORMATSUPPORT_FORMAT_NOT_SUPPORTED:
          ::libc::c_uint =
    2097402;
pub const D3D11_MESSAGE_ID_DEVICE_CSSETUNORDEREDACCESSVIEWS_INVALIDVIEW:
          ::libc::c_uint =
    2097403;
pub const D3D11_MESSAGE_ID_DEVICE_CSSETUNORDEREDACCESSVIEWS_INVALIDOFFSET:
          ::libc::c_uint =
    2097404;
pub const D3D11_MESSAGE_ID_DEVICE_CSSETUNORDEREDACCESSVIEWS_TOOMANYVIEWS:
          ::libc::c_uint =
    2097405;
pub const D3D11_MESSAGE_ID_CLEARUNORDEREDACCESSVIEWFLOAT_INVALIDFORMAT:
          ::libc::c_uint =
    2097406;
pub const D3D11_MESSAGE_ID_DEVICE_UNORDEREDACCESSVIEW_COUNTER_UNSUPPORTED:
          ::libc::c_uint =
    2097407;
pub const D3D11_MESSAGE_ID_REF_WARNING: ::libc::c_uint = 2097408;
pub const D3D11_MESSAGE_ID_D3D11_MESSAGES_END: ::libc::c_uint = 2097409;
pub type D3D11_MESSAGE_ID = Enum_D3D11_MESSAGE_ID;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_D3D11_MESSAGE {
    pub Category: D3D11_MESSAGE_CATEGORY,
    pub Severity: D3D11_MESSAGE_SEVERITY,
    pub ID: D3D11_MESSAGE_ID,
    pub pDescription: *const ::libc::c_char,
    pub DescriptionByteLength: SIZE_T,
}
impl ::std::default::Default for Struct_D3D11_MESSAGE {
    fn default() -> Struct_D3D11_MESSAGE { unsafe { ::std::mem::zeroed() } }
}
pub type D3D11_MESSAGE = Struct_D3D11_MESSAGE;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_D3D11_INFO_QUEUE_FILTER_DESC {
    pub NumCategories: UINT,
    pub pCategoryList: *mut D3D11_MESSAGE_CATEGORY,
    pub NumSeverities: UINT,
    pub pSeverityList: *mut D3D11_MESSAGE_SEVERITY,
    pub NumIDs: UINT,
    pub pIDList: *mut D3D11_MESSAGE_ID,
}
impl ::std::default::Default for Struct_D3D11_INFO_QUEUE_FILTER_DESC {
    fn default() -> Struct_D3D11_INFO_QUEUE_FILTER_DESC {
        unsafe { ::std::mem::zeroed() }
    }
}
pub type D3D11_INFO_QUEUE_FILTER_DESC = Struct_D3D11_INFO_QUEUE_FILTER_DESC;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_D3D11_INFO_QUEUE_FILTER {
    pub AllowList: D3D11_INFO_QUEUE_FILTER_DESC,
    pub DenyList: D3D11_INFO_QUEUE_FILTER_DESC,
}
impl ::std::default::Default for Struct_D3D11_INFO_QUEUE_FILTER {
    fn default() -> Struct_D3D11_INFO_QUEUE_FILTER {
        unsafe { ::std::mem::zeroed() }
    }
}
pub type D3D11_INFO_QUEUE_FILTER = Struct_D3D11_INFO_QUEUE_FILTER;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ID3D11InfoQueueVtbl {
    pub QueryInterface: ::std::option::Option<extern "C" fn
                                                  (This: *mut ID3D11InfoQueue,
                                                   riid: *const IID,
                                                   ppvObject:
                                                       *mut *mut ::libc::c_void)
                                                  -> HRESULT>,
    pub AddRef: ::std::option::Option<extern "C" fn
                                          (This: *mut ID3D11InfoQueue)
                                          -> ULONG>,
    pub Release: ::std::option::Option<extern "C" fn
                                           (This: *mut ID3D11InfoQueue)
                                           -> ULONG>,
    pub SetMessageCountLimit: ::std::option::Option<extern "C" fn
                                                        (This:
                                                             *mut ID3D11InfoQueue,
                                                         MessageCountLimit:
                                                             UINT64)
                                                        -> HRESULT>,
    pub ClearStoredMessages: ::std::option::Option<extern "C" fn
                                                       (This:
                                                            *mut ID3D11InfoQueue)
                                                       -> ()>,
    pub GetMessageA: ::std::option::Option<extern "C" fn
                                               (This: *mut ID3D11InfoQueue,
                                                MessageIndex: UINT64,
                                                pMessage: *mut D3D11_MESSAGE,
                                                pMessageByteLength:
                                                    *mut SIZE_T) -> HRESULT>,
    pub GetNumMessagesAllowedByStorageFilter: ::std::option::Option<extern "C" fn
                                                                        (This:
                                                                             *mut ID3D11InfoQueue)
                                                                        ->
                                                                            UINT64>,
    pub GetNumMessagesDeniedByStorageFilter: ::std::option::Option<extern "C" fn
                                                                       (This:
                                                                            *mut ID3D11InfoQueue)
                                                                       ->
                                                                           UINT64>,
    pub GetNumStoredMessages: ::std::option::Option<extern "C" fn
                                                        (This:
                                                             *mut ID3D11InfoQueue)
                                                        -> UINT64>,
    pub GetNumStoredMessagesAllowedByRetrievalFilter: ::std::option::Option<extern "C" fn
                                                                                (This:
                                                                                     *mut ID3D11InfoQueue)
                                                                                ->
                                                                                    UINT64>,
    pub GetNumMessagesDiscardedByMessageCountLimit: ::std::option::Option<extern "C" fn
                                                                              (This:
                                                                                   *mut ID3D11InfoQueue)
                                                                              ->
                                                                                  UINT64>,
    pub GetMessageCountLimit: ::std::option::Option<extern "C" fn
                                                        (This:
                                                             *mut ID3D11InfoQueue)
                                                        -> UINT64>,
    pub AddStorageFilterEntries: ::std::option::Option<extern "C" fn
                                                           (This:
                                                                *mut ID3D11InfoQueue,
                                                            pFilter:
                                                                *mut D3D11_INFO_QUEUE_FILTER)
                                                           -> HRESULT>,
    pub GetStorageFilter: ::std::option::Option<extern "C" fn
                                                    (This:
                                                         *mut ID3D11InfoQueue,
                                                     pFilter:
                                                         *mut D3D11_INFO_QUEUE_FILTER,
                                                     pFilterByteLength:
                                                         *mut SIZE_T)
                                                    -> HRESULT>,
    pub ClearStorageFilter: ::std::option::Option<extern "C" fn
                                                      (This:
                                                           *mut ID3D11InfoQueue)
                                                      -> ()>,
    pub PushEmptyStorageFilter: ::std::option::Option<extern "C" fn
                                                          (This:
                                                               *mut ID3D11InfoQueue)
                                                          -> HRESULT>,
    pub PushCopyOfStorageFilter: ::std::option::Option<extern "C" fn
                                                           (This:
                                                                *mut ID3D11InfoQueue)
                                                           -> HRESULT>,
    pub PushStorageFilter: ::std::option::Option<extern "C" fn
                                                     (This:
                                                          *mut ID3D11InfoQueue,
                                                      pFilter:
                                                          *mut D3D11_INFO_QUEUE_FILTER)
                                                     -> HRESULT>,
    pub PopStorageFilter: ::std::option::Option<extern "C" fn
                                                    (This:
                                                         *mut ID3D11InfoQueue)
                                                    -> ()>,
    pub GetStorageFilterStackSize: ::std::option::Option<extern "C" fn
                                                             (This:
                                                                  *mut ID3D11InfoQueue)
                                                             -> UINT>,
    pub AddRetrievalFilterEntries: ::std::option::Option<extern "C" fn
                                                             (This:
                                                                  *mut ID3D11InfoQueue,
                                                              pFilter:
                                                                  *mut D3D11_INFO_QUEUE_FILTER)
                                                             -> HRESULT>,
    pub GetRetrievalFilter: ::std::option::Option<extern "C" fn
                                                      (This:
                                                           *mut ID3D11InfoQueue,
                                                       pFilter:
                                                           *mut D3D11_INFO_QUEUE_FILTER,
                                                       pFilterByteLength:
                                                           *mut SIZE_T)
                                                      -> HRESULT>,
    pub ClearRetrievalFilter: ::std::option::Option<extern "C" fn
                                                        (This:
                                                             *mut ID3D11InfoQueue)
                                                        -> ()>,
    pub PushEmptyRetrievalFilter: ::std::option::Option<extern "C" fn
                                                            (This:
                                                                 *mut ID3D11InfoQueue)
                                                            -> HRESULT>,
    pub PushCopyOfRetrievalFilter: ::std::option::Option<extern "C" fn
                                                             (This:
                                                                  *mut ID3D11InfoQueue)
                                                             -> HRESULT>,
    pub PushRetrievalFilter: ::std::option::Option<extern "C" fn
                                                       (This:
                                                            *mut ID3D11InfoQueue,
                                                        pFilter:
                                                            *mut D3D11_INFO_QUEUE_FILTER)
                                                       -> HRESULT>,
    pub PopRetrievalFilter: ::std::option::Option<extern "C" fn
                                                      (This:
                                                           *mut ID3D11InfoQueue)
                                                      -> ()>,
    pub GetRetrievalFilterStackSize: ::std::option::Option<extern "C" fn
                                                               (This:
                                                                    *mut ID3D11InfoQueue)
                                                               -> UINT>,
    pub AddMessage: ::std::option::Option<extern "C" fn
                                              (This: *mut ID3D11InfoQueue,
                                               Category:
                                                   D3D11_MESSAGE_CATEGORY,
                                               Severity:
                                                   D3D11_MESSAGE_SEVERITY,
                                               ID: D3D11_MESSAGE_ID,
                                               pDescription: LPCSTR)
                                              -> HRESULT>,
    pub AddApplicationMessage: ::std::option::Option<extern "C" fn
                                                         (This:
                                                              *mut ID3D11InfoQueue,
                                                          Severity:
                                                              D3D11_MESSAGE_SEVERITY,
                                                          pDescription:
                                                              LPCSTR)
                                                         -> HRESULT>,
    pub SetBreakOnCategory: ::std::option::Option<extern "C" fn
                                                      (This:
                                                           *mut ID3D11InfoQueue,
                                                       Category:
                                                           D3D11_MESSAGE_CATEGORY,
                                                       bEnable: BOOL)
                                                      -> HRESULT>,
    pub SetBreakOnSeverity: ::std::option::Option<extern "C" fn
                                                      (This:
                                                           *mut ID3D11InfoQueue,
                                                       Severity:
                                                           D3D11_MESSAGE_SEVERITY,
                                                       bEnable: BOOL)
                                                      -> HRESULT>,
    pub SetBreakOnID: ::std::option::Option<extern "C" fn
                                                (This: *mut ID3D11InfoQueue,
                                                 ID: D3D11_MESSAGE_ID,
                                                 bEnable: BOOL) -> HRESULT>,
    pub GetBreakOnCategory: ::std::option::Option<extern "C" fn
                                                      (This:
                                                           *mut ID3D11InfoQueue,
                                                       Category:
                                                           D3D11_MESSAGE_CATEGORY)
                                                      -> BOOL>,
    pub GetBreakOnSeverity: ::std::option::Option<extern "C" fn
                                                      (This:
                                                           *mut ID3D11InfoQueue,
                                                       Severity:
                                                           D3D11_MESSAGE_SEVERITY)
                                                      -> BOOL>,
    pub GetBreakOnID: ::std::option::Option<extern "C" fn
                                                (This: *mut ID3D11InfoQueue,
                                                 ID: D3D11_MESSAGE_ID)
                                                -> BOOL>,
    pub SetMuteDebugOutput: ::std::option::Option<extern "C" fn
                                                      (This:
                                                           *mut ID3D11InfoQueue,
                                                       bMute: BOOL) -> ()>,
    pub GetMuteDebugOutput: ::std::option::Option<extern "C" fn
                                                      (This:
                                                           *mut ID3D11InfoQueue)
                                                      -> BOOL>,
}
impl ::std::default::Default for Struct_ID3D11InfoQueueVtbl {
    fn default() -> Struct_ID3D11InfoQueueVtbl {
        unsafe { ::std::mem::zeroed() }
    }
}
pub type ID3D11InfoQueueVtbl = Struct_ID3D11InfoQueueVtbl;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ID3D11InfoQueue {
    pub lpVtbl: *mut Struct_ID3D11InfoQueueVtbl,
}
impl ::std::default::Default for Struct_ID3D11InfoQueue {
    fn default() -> Struct_ID3D11InfoQueue { unsafe { ::std::mem::zeroed() } }
}
extern "C" {
    pub static mut __MIDL_itf_d3d11sdklayers_0000_0000_v0_0_c_ifspec:
               RPC_IF_HANDLE;
    pub static mut __MIDL_itf_d3d11sdklayers_0000_0000_v0_0_s_ifspec:
               RPC_IF_HANDLE;
    pub static IID_ID3D11Debug: GUID;
    pub static IID_ID3D11SwitchToRef: GUID;
    pub static mut __MIDL_itf_d3d11sdklayers_0000_0002_v0_0_c_ifspec:
               RPC_IF_HANDLE;
    pub static mut __MIDL_itf_d3d11sdklayers_0000_0002_v0_0_s_ifspec:
               RPC_IF_HANDLE;
    pub static IID_ID3D11InfoQueue: GUID;
    pub static mut __MIDL_itf_d3d11sdklayers_0000_0003_v0_0_c_ifspec:
               RPC_IF_HANDLE;
    pub static mut __MIDL_itf_d3d11sdklayers_0000_0003_v0_0_s_ifspec:
               RPC_IF_HANDLE;
}
