/* automatically generated by rust-bindgen */

pub type ID3D10Blob = Struct_ID3D10Blob;
pub type Enum_D3D_DRIVER_TYPE = ::libc::c_uint;
pub const D3D_DRIVER_TYPE_UNKNOWN: ::libc::c_uint = 0;
pub const D3D_DRIVER_TYPE_HARDWARE: ::libc::c_uint = 1;
pub const D3D_DRIVER_TYPE_REFERENCE: ::libc::c_uint = 2;
pub const D3D_DRIVER_TYPE_NULL: ::libc::c_uint = 3;
pub const D3D_DRIVER_TYPE_SOFTWARE: ::libc::c_uint = 4;
pub const D3D_DRIVER_TYPE_WARP: ::libc::c_uint = 5;
pub type D3D_DRIVER_TYPE = Enum_D3D_DRIVER_TYPE;
pub type Enum_D3D_FEATURE_LEVEL = ::libc::c_uint;
pub const D3D_FEATURE_LEVEL_9_1: ::libc::c_uint = 37120;
pub const D3D_FEATURE_LEVEL_9_2: ::libc::c_uint = 37376;
pub const D3D_FEATURE_LEVEL_9_3: ::libc::c_uint = 37632;
pub const D3D_FEATURE_LEVEL_10_0: ::libc::c_uint = 40960;
pub const D3D_FEATURE_LEVEL_10_1: ::libc::c_uint = 41216;
pub const D3D_FEATURE_LEVEL_11_0: ::libc::c_uint = 45056;
pub type D3D_FEATURE_LEVEL = Enum_D3D_FEATURE_LEVEL;
pub type Enum_D3D_PRIMITIVE_TOPOLOGY = ::libc::c_uint;
pub const D3D_PRIMITIVE_TOPOLOGY_UNDEFINED: ::libc::c_uint = 0;
pub const D3D_PRIMITIVE_TOPOLOGY_POINTLIST: ::libc::c_uint = 1;
pub const D3D_PRIMITIVE_TOPOLOGY_LINELIST: ::libc::c_uint = 2;
pub const D3D_PRIMITIVE_TOPOLOGY_LINESTRIP: ::libc::c_uint = 3;
pub const D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST: ::libc::c_uint = 4;
pub const D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP: ::libc::c_uint = 5;
pub const D3D_PRIMITIVE_TOPOLOGY_LINELIST_ADJ: ::libc::c_uint = 10;
pub const D3D_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ: ::libc::c_uint = 11;
pub const D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ: ::libc::c_uint = 12;
pub const D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ: ::libc::c_uint = 13;
pub const D3D_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    33;
pub const D3D_PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    34;
pub const D3D_PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    35;
pub const D3D_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    36;
pub const D3D_PRIMITIVE_TOPOLOGY_5_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    37;
pub const D3D_PRIMITIVE_TOPOLOGY_6_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    38;
pub const D3D_PRIMITIVE_TOPOLOGY_7_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    39;
pub const D3D_PRIMITIVE_TOPOLOGY_8_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    40;
pub const D3D_PRIMITIVE_TOPOLOGY_9_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    41;
pub const D3D_PRIMITIVE_TOPOLOGY_10_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    42;
pub const D3D_PRIMITIVE_TOPOLOGY_11_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    43;
pub const D3D_PRIMITIVE_TOPOLOGY_12_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    44;
pub const D3D_PRIMITIVE_TOPOLOGY_13_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    45;
pub const D3D_PRIMITIVE_TOPOLOGY_14_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    46;
pub const D3D_PRIMITIVE_TOPOLOGY_15_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    47;
pub const D3D_PRIMITIVE_TOPOLOGY_16_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    48;
pub const D3D_PRIMITIVE_TOPOLOGY_17_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    49;
pub const D3D_PRIMITIVE_TOPOLOGY_18_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    50;
pub const D3D_PRIMITIVE_TOPOLOGY_19_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    51;
pub const D3D_PRIMITIVE_TOPOLOGY_20_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    52;
pub const D3D_PRIMITIVE_TOPOLOGY_21_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    53;
pub const D3D_PRIMITIVE_TOPOLOGY_22_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    54;
pub const D3D_PRIMITIVE_TOPOLOGY_23_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    55;
pub const D3D_PRIMITIVE_TOPOLOGY_24_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    56;
pub const D3D_PRIMITIVE_TOPOLOGY_25_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    57;
pub const D3D_PRIMITIVE_TOPOLOGY_26_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    58;
pub const D3D_PRIMITIVE_TOPOLOGY_27_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    59;
pub const D3D_PRIMITIVE_TOPOLOGY_28_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    60;
pub const D3D_PRIMITIVE_TOPOLOGY_29_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    61;
pub const D3D_PRIMITIVE_TOPOLOGY_30_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    62;
pub const D3D_PRIMITIVE_TOPOLOGY_31_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    63;
pub const D3D_PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    64;
pub const D3D10_PRIMITIVE_TOPOLOGY_UNDEFINED: ::libc::c_uint = 0;
pub const D3D10_PRIMITIVE_TOPOLOGY_POINTLIST: ::libc::c_uint = 1;
pub const D3D10_PRIMITIVE_TOPOLOGY_LINELIST: ::libc::c_uint = 2;
pub const D3D10_PRIMITIVE_TOPOLOGY_LINESTRIP: ::libc::c_uint = 3;
pub const D3D10_PRIMITIVE_TOPOLOGY_TRIANGLELIST: ::libc::c_uint = 4;
pub const D3D10_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP: ::libc::c_uint = 5;
pub const D3D10_PRIMITIVE_TOPOLOGY_LINELIST_ADJ: ::libc::c_uint = 10;
pub const D3D10_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ: ::libc::c_uint = 11;
pub const D3D10_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ: ::libc::c_uint = 12;
pub const D3D10_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ: ::libc::c_uint = 13;
pub const D3D11_PRIMITIVE_TOPOLOGY_UNDEFINED: ::libc::c_uint = 0;
pub const D3D11_PRIMITIVE_TOPOLOGY_POINTLIST: ::libc::c_uint = 1;
pub const D3D11_PRIMITIVE_TOPOLOGY_LINELIST: ::libc::c_uint = 2;
pub const D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP: ::libc::c_uint = 3;
pub const D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST: ::libc::c_uint = 4;
pub const D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP: ::libc::c_uint = 5;
pub const D3D11_PRIMITIVE_TOPOLOGY_LINELIST_ADJ: ::libc::c_uint = 10;
pub const D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ: ::libc::c_uint = 11;
pub const D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ: ::libc::c_uint = 12;
pub const D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ: ::libc::c_uint = 13;
pub const D3D11_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    33;
pub const D3D11_PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    34;
pub const D3D11_PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    35;
pub const D3D11_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    36;
pub const D3D11_PRIMITIVE_TOPOLOGY_5_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    37;
pub const D3D11_PRIMITIVE_TOPOLOGY_6_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    38;
pub const D3D11_PRIMITIVE_TOPOLOGY_7_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    39;
pub const D3D11_PRIMITIVE_TOPOLOGY_8_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    40;
pub const D3D11_PRIMITIVE_TOPOLOGY_9_CONTROL_POINT_PATCHLIST: ::libc::c_uint =
    41;
pub const D3D11_PRIMITIVE_TOPOLOGY_10_CONTROL_POINT_PATCHLIST: ::libc::c_uint
          =
    42;
pub const D3D11_PRIMITIVE_TOPOLOGY_11_CONTROL_POINT_PATCHLIST: ::libc::c_uint
          =
    43;
pub const D3D11_PRIMITIVE_TOPOLOGY_12_CONTROL_POINT_PATCHLIST: ::libc::c_uint
          =
    44;
pub const D3D11_PRIMITIVE_TOPOLOGY_13_CONTROL_POINT_PATCHLIST: ::libc::c_uint
          =
    45;
pub const D3D11_PRIMITIVE_TOPOLOGY_14_CONTROL_POINT_PATCHLIST: ::libc::c_uint
          =
    46;
pub const D3D11_PRIMITIVE_TOPOLOGY_15_CONTROL_POINT_PATCHLIST: ::libc::c_uint
          =
    47;
pub const D3D11_PRIMITIVE_TOPOLOGY_16_CONTROL_POINT_PATCHLIST: ::libc::c_uint
          =
    48;
pub const D3D11_PRIMITIVE_TOPOLOGY_17_CONTROL_POINT_PATCHLIST: ::libc::c_uint
          =
    49;
pub const D3D11_PRIMITIVE_TOPOLOGY_18_CONTROL_POINT_PATCHLIST: ::libc::c_uint
          =
    50;
pub const D3D11_PRIMITIVE_TOPOLOGY_19_CONTROL_POINT_PATCHLIST: ::libc::c_uint
          =
    51;
pub const D3D11_PRIMITIVE_TOPOLOGY_20_CONTROL_POINT_PATCHLIST: ::libc::c_uint
          =
    52;
pub const D3D11_PRIMITIVE_TOPOLOGY_21_CONTROL_POINT_PATCHLIST: ::libc::c_uint
          =
    53;
pub const D3D11_PRIMITIVE_TOPOLOGY_22_CONTROL_POINT_PATCHLIST: ::libc::c_uint
          =
    54;
pub const D3D11_PRIMITIVE_TOPOLOGY_23_CONTROL_POINT_PATCHLIST: ::libc::c_uint
          =
    55;
pub const D3D11_PRIMITIVE_TOPOLOGY_24_CONTROL_POINT_PATCHLIST: ::libc::c_uint
          =
    56;
pub const D3D11_PRIMITIVE_TOPOLOGY_25_CONTROL_POINT_PATCHLIST: ::libc::c_uint
          =
    57;
pub const D3D11_PRIMITIVE_TOPOLOGY_26_CONTROL_POINT_PATCHLIST: ::libc::c_uint
          =
    58;
pub const D3D11_PRIMITIVE_TOPOLOGY_27_CONTROL_POINT_PATCHLIST: ::libc::c_uint
          =
    59;
pub const D3D11_PRIMITIVE_TOPOLOGY_28_CONTROL_POINT_PATCHLIST: ::libc::c_uint
          =
    60;
pub const D3D11_PRIMITIVE_TOPOLOGY_29_CONTROL_POINT_PATCHLIST: ::libc::c_uint
          =
    61;
pub const D3D11_PRIMITIVE_TOPOLOGY_30_CONTROL_POINT_PATCHLIST: ::libc::c_uint
          =
    62;
pub const D3D11_PRIMITIVE_TOPOLOGY_31_CONTROL_POINT_PATCHLIST: ::libc::c_uint
          =
    63;
pub const D3D11_PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST: ::libc::c_uint
          =
    64;
pub type D3D_PRIMITIVE_TOPOLOGY = Enum_D3D_PRIMITIVE_TOPOLOGY;
pub type Enum_D3D_PRIMITIVE = ::libc::c_uint;
pub const D3D_PRIMITIVE_UNDEFINED: ::libc::c_uint = 0;
pub const D3D_PRIMITIVE_POINT: ::libc::c_uint = 1;
pub const D3D_PRIMITIVE_LINE: ::libc::c_uint = 2;
pub const D3D_PRIMITIVE_TRIANGLE: ::libc::c_uint = 3;
pub const D3D_PRIMITIVE_LINE_ADJ: ::libc::c_uint = 6;
pub const D3D_PRIMITIVE_TRIANGLE_ADJ: ::libc::c_uint = 7;
pub const D3D_PRIMITIVE_1_CONTROL_POINT_PATCH: ::libc::c_uint = 8;
pub const D3D_PRIMITIVE_2_CONTROL_POINT_PATCH: ::libc::c_uint = 9;
pub const D3D_PRIMITIVE_3_CONTROL_POINT_PATCH: ::libc::c_uint = 10;
pub const D3D_PRIMITIVE_4_CONTROL_POINT_PATCH: ::libc::c_uint = 11;
pub const D3D_PRIMITIVE_5_CONTROL_POINT_PATCH: ::libc::c_uint = 12;
pub const D3D_PRIMITIVE_6_CONTROL_POINT_PATCH: ::libc::c_uint = 13;
pub const D3D_PRIMITIVE_7_CONTROL_POINT_PATCH: ::libc::c_uint = 14;
pub const D3D_PRIMITIVE_8_CONTROL_POINT_PATCH: ::libc::c_uint = 15;
pub const D3D_PRIMITIVE_9_CONTROL_POINT_PATCH: ::libc::c_uint = 16;
pub const D3D_PRIMITIVE_10_CONTROL_POINT_PATCH: ::libc::c_uint = 17;
pub const D3D_PRIMITIVE_11_CONTROL_POINT_PATCH: ::libc::c_uint = 18;
pub const D3D_PRIMITIVE_12_CONTROL_POINT_PATCH: ::libc::c_uint = 19;
pub const D3D_PRIMITIVE_13_CONTROL_POINT_PATCH: ::libc::c_uint = 20;
pub const D3D_PRIMITIVE_14_CONTROL_POINT_PATCH: ::libc::c_uint = 21;
pub const D3D_PRIMITIVE_15_CONTROL_POINT_PATCH: ::libc::c_uint = 22;
pub const D3D_PRIMITIVE_16_CONTROL_POINT_PATCH: ::libc::c_uint = 23;
pub const D3D_PRIMITIVE_17_CONTROL_POINT_PATCH: ::libc::c_uint = 24;
pub const D3D_PRIMITIVE_18_CONTROL_POINT_PATCH: ::libc::c_uint = 25;
pub const D3D_PRIMITIVE_19_CONTROL_POINT_PATCH: ::libc::c_uint = 26;
pub const D3D_PRIMITIVE_20_CONTROL_POINT_PATCH: ::libc::c_uint = 28;
pub const D3D_PRIMITIVE_21_CONTROL_POINT_PATCH: ::libc::c_uint = 29;
pub const D3D_PRIMITIVE_22_CONTROL_POINT_PATCH: ::libc::c_uint = 30;
pub const D3D_PRIMITIVE_23_CONTROL_POINT_PATCH: ::libc::c_uint = 31;
pub const D3D_PRIMITIVE_24_CONTROL_POINT_PATCH: ::libc::c_uint = 32;
pub const D3D_PRIMITIVE_25_CONTROL_POINT_PATCH: ::libc::c_uint = 33;
pub const D3D_PRIMITIVE_26_CONTROL_POINT_PATCH: ::libc::c_uint = 34;
pub const D3D_PRIMITIVE_27_CONTROL_POINT_PATCH: ::libc::c_uint = 35;
pub const D3D_PRIMITIVE_28_CONTROL_POINT_PATCH: ::libc::c_uint = 36;
pub const D3D_PRIMITIVE_29_CONTROL_POINT_PATCH: ::libc::c_uint = 37;
pub const D3D_PRIMITIVE_30_CONTROL_POINT_PATCH: ::libc::c_uint = 38;
pub const D3D_PRIMITIVE_31_CONTROL_POINT_PATCH: ::libc::c_uint = 39;
pub const D3D_PRIMITIVE_32_CONTROL_POINT_PATCH: ::libc::c_uint = 40;
pub const D3D10_PRIMITIVE_UNDEFINED: ::libc::c_uint = 0;
pub const D3D10_PRIMITIVE_POINT: ::libc::c_uint = 1;
pub const D3D10_PRIMITIVE_LINE: ::libc::c_uint = 2;
pub const D3D10_PRIMITIVE_TRIANGLE: ::libc::c_uint = 3;
pub const D3D10_PRIMITIVE_LINE_ADJ: ::libc::c_uint = 6;
pub const D3D10_PRIMITIVE_TRIANGLE_ADJ: ::libc::c_uint = 7;
pub const D3D11_PRIMITIVE_UNDEFINED: ::libc::c_uint = 0;
pub const D3D11_PRIMITIVE_POINT: ::libc::c_uint = 1;
pub const D3D11_PRIMITIVE_LINE: ::libc::c_uint = 2;
pub const D3D11_PRIMITIVE_TRIANGLE: ::libc::c_uint = 3;
pub const D3D11_PRIMITIVE_LINE_ADJ: ::libc::c_uint = 6;
pub const D3D11_PRIMITIVE_TRIANGLE_ADJ: ::libc::c_uint = 7;
pub const D3D11_PRIMITIVE_1_CONTROL_POINT_PATCH: ::libc::c_uint = 8;
pub const D3D11_PRIMITIVE_2_CONTROL_POINT_PATCH: ::libc::c_uint = 9;
pub const D3D11_PRIMITIVE_3_CONTROL_POINT_PATCH: ::libc::c_uint = 10;
pub const D3D11_PRIMITIVE_4_CONTROL_POINT_PATCH: ::libc::c_uint = 11;
pub const D3D11_PRIMITIVE_5_CONTROL_POINT_PATCH: ::libc::c_uint = 12;
pub const D3D11_PRIMITIVE_6_CONTROL_POINT_PATCH: ::libc::c_uint = 13;
pub const D3D11_PRIMITIVE_7_CONTROL_POINT_PATCH: ::libc::c_uint = 14;
pub const D3D11_PRIMITIVE_8_CONTROL_POINT_PATCH: ::libc::c_uint = 15;
pub const D3D11_PRIMITIVE_9_CONTROL_POINT_PATCH: ::libc::c_uint = 16;
pub const D3D11_PRIMITIVE_10_CONTROL_POINT_PATCH: ::libc::c_uint = 17;
pub const D3D11_PRIMITIVE_11_CONTROL_POINT_PATCH: ::libc::c_uint = 18;
pub const D3D11_PRIMITIVE_12_CONTROL_POINT_PATCH: ::libc::c_uint = 19;
pub const D3D11_PRIMITIVE_13_CONTROL_POINT_PATCH: ::libc::c_uint = 20;
pub const D3D11_PRIMITIVE_14_CONTROL_POINT_PATCH: ::libc::c_uint = 21;
pub const D3D11_PRIMITIVE_15_CONTROL_POINT_PATCH: ::libc::c_uint = 22;
pub const D3D11_PRIMITIVE_16_CONTROL_POINT_PATCH: ::libc::c_uint = 23;
pub const D3D11_PRIMITIVE_17_CONTROL_POINT_PATCH: ::libc::c_uint = 24;
pub const D3D11_PRIMITIVE_18_CONTROL_POINT_PATCH: ::libc::c_uint = 25;
pub const D3D11_PRIMITIVE_19_CONTROL_POINT_PATCH: ::libc::c_uint = 26;
pub const D3D11_PRIMITIVE_20_CONTROL_POINT_PATCH: ::libc::c_uint = 28;
pub const D3D11_PRIMITIVE_21_CONTROL_POINT_PATCH: ::libc::c_uint = 29;
pub const D3D11_PRIMITIVE_22_CONTROL_POINT_PATCH: ::libc::c_uint = 30;
pub const D3D11_PRIMITIVE_23_CONTROL_POINT_PATCH: ::libc::c_uint = 31;
pub const D3D11_PRIMITIVE_24_CONTROL_POINT_PATCH: ::libc::c_uint = 32;
pub const D3D11_PRIMITIVE_25_CONTROL_POINT_PATCH: ::libc::c_uint = 33;
pub const D3D11_PRIMITIVE_26_CONTROL_POINT_PATCH: ::libc::c_uint = 34;
pub const D3D11_PRIMITIVE_27_CONTROL_POINT_PATCH: ::libc::c_uint = 35;
pub const D3D11_PRIMITIVE_28_CONTROL_POINT_PATCH: ::libc::c_uint = 36;
pub const D3D11_PRIMITIVE_29_CONTROL_POINT_PATCH: ::libc::c_uint = 37;
pub const D3D11_PRIMITIVE_30_CONTROL_POINT_PATCH: ::libc::c_uint = 38;
pub const D3D11_PRIMITIVE_31_CONTROL_POINT_PATCH: ::libc::c_uint = 39;
pub const D3D11_PRIMITIVE_32_CONTROL_POINT_PATCH: ::libc::c_uint = 40;
pub type D3D_PRIMITIVE = Enum_D3D_PRIMITIVE;
pub type Enum_D3D_SRV_DIMENSION = ::libc::c_uint;
pub const D3D_SRV_DIMENSION_UNKNOWN: ::libc::c_uint = 0;
pub const D3D_SRV_DIMENSION_BUFFER: ::libc::c_uint = 1;
pub const D3D_SRV_DIMENSION_TEXTURE1D: ::libc::c_uint = 2;
pub const D3D_SRV_DIMENSION_TEXTURE1DARRAY: ::libc::c_uint = 3;
pub const D3D_SRV_DIMENSION_TEXTURE2D: ::libc::c_uint = 4;
pub const D3D_SRV_DIMENSION_TEXTURE2DARRAY: ::libc::c_uint = 5;
pub const D3D_SRV_DIMENSION_TEXTURE2DMS: ::libc::c_uint = 6;
pub const D3D_SRV_DIMENSION_TEXTURE2DMSARRAY: ::libc::c_uint = 7;
pub const D3D_SRV_DIMENSION_TEXTURE3D: ::libc::c_uint = 8;
pub const D3D_SRV_DIMENSION_TEXTURECUBE: ::libc::c_uint = 9;
pub const D3D_SRV_DIMENSION_TEXTURECUBEARRAY: ::libc::c_uint = 10;
pub const D3D_SRV_DIMENSION_BUFFEREX: ::libc::c_uint = 11;
pub const D3D10_SRV_DIMENSION_UNKNOWN: ::libc::c_uint = 0;
pub const D3D10_SRV_DIMENSION_BUFFER: ::libc::c_uint = 1;
pub const D3D10_SRV_DIMENSION_TEXTURE1D: ::libc::c_uint = 2;
pub const D3D10_SRV_DIMENSION_TEXTURE1DARRAY: ::libc::c_uint = 3;
pub const D3D10_SRV_DIMENSION_TEXTURE2D: ::libc::c_uint = 4;
pub const D3D10_SRV_DIMENSION_TEXTURE2DARRAY: ::libc::c_uint = 5;
pub const D3D10_SRV_DIMENSION_TEXTURE2DMS: ::libc::c_uint = 6;
pub const D3D10_SRV_DIMENSION_TEXTURE2DMSARRAY: ::libc::c_uint = 7;
pub const D3D10_SRV_DIMENSION_TEXTURE3D: ::libc::c_uint = 8;
pub const D3D10_SRV_DIMENSION_TEXTURECUBE: ::libc::c_uint = 9;
pub const D3D10_1_SRV_DIMENSION_UNKNOWN: ::libc::c_uint = 0;
pub const D3D10_1_SRV_DIMENSION_BUFFER: ::libc::c_uint = 1;
pub const D3D10_1_SRV_DIMENSION_TEXTURE1D: ::libc::c_uint = 2;
pub const D3D10_1_SRV_DIMENSION_TEXTURE1DARRAY: ::libc::c_uint = 3;
pub const D3D10_1_SRV_DIMENSION_TEXTURE2D: ::libc::c_uint = 4;
pub const D3D10_1_SRV_DIMENSION_TEXTURE2DARRAY: ::libc::c_uint = 5;
pub const D3D10_1_SRV_DIMENSION_TEXTURE2DMS: ::libc::c_uint = 6;
pub const D3D10_1_SRV_DIMENSION_TEXTURE2DMSARRAY: ::libc::c_uint = 7;
pub const D3D10_1_SRV_DIMENSION_TEXTURE3D: ::libc::c_uint = 8;
pub const D3D10_1_SRV_DIMENSION_TEXTURECUBE: ::libc::c_uint = 9;
pub const D3D10_1_SRV_DIMENSION_TEXTURECUBEARRAY: ::libc::c_uint = 10;
pub const D3D11_SRV_DIMENSION_UNKNOWN: ::libc::c_uint = 0;
pub const D3D11_SRV_DIMENSION_BUFFER: ::libc::c_uint = 1;
pub const D3D11_SRV_DIMENSION_TEXTURE1D: ::libc::c_uint = 2;
pub const D3D11_SRV_DIMENSION_TEXTURE1DARRAY: ::libc::c_uint = 3;
pub const D3D11_SRV_DIMENSION_TEXTURE2D: ::libc::c_uint = 4;
pub const D3D11_SRV_DIMENSION_TEXTURE2DARRAY: ::libc::c_uint = 5;
pub const D3D11_SRV_DIMENSION_TEXTURE2DMS: ::libc::c_uint = 6;
pub const D3D11_SRV_DIMENSION_TEXTURE2DMSARRAY: ::libc::c_uint = 7;
pub const D3D11_SRV_DIMENSION_TEXTURE3D: ::libc::c_uint = 8;
pub const D3D11_SRV_DIMENSION_TEXTURECUBE: ::libc::c_uint = 9;
pub const D3D11_SRV_DIMENSION_TEXTURECUBEARRAY: ::libc::c_uint = 10;
pub const D3D11_SRV_DIMENSION_BUFFEREX: ::libc::c_uint = 11;
pub type D3D_SRV_DIMENSION = Enum_D3D_SRV_DIMENSION;
#[repr(C)]
#[derive(Copy)]
pub struct Struct__D3D_SHADER_MACRO {
    pub Name: LPCSTR,
    pub Definition: LPCSTR,
}
impl ::std::default::Default for Struct__D3D_SHADER_MACRO {
    fn default() -> Struct__D3D_SHADER_MACRO {
        unsafe { ::std::mem::zeroed() }
    }
}
pub type D3D_SHADER_MACRO = Struct__D3D_SHADER_MACRO;
pub type LPD3D_SHADER_MACRO = *mut Struct__D3D_SHADER_MACRO;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ID3D10BlobVtbl {
    pub QueryInterface: ::std::option::Option<extern "C" fn
                                                  (This: *mut ID3D10Blob,
                                                   riid: *const IID,
                                                   ppvObject:
                                                       *mut *mut ::libc::c_void)
                                                  -> HRESULT>,
    pub AddRef: ::std::option::Option<extern "C" fn(This: *mut ID3D10Blob)
                                          -> ULONG>,
    pub Release: ::std::option::Option<extern "C" fn(This: *mut ID3D10Blob)
                                           -> ULONG>,
    pub GetBufferPointer: ::std::option::Option<extern "C" fn
                                                    (This: *mut ID3D10Blob)
                                                    -> LPVOID>,
    pub GetBufferSize: ::std::option::Option<extern "C" fn
                                                 (This: *mut ID3D10Blob)
                                                 -> SIZE_T>,
}
impl ::std::default::Default for Struct_ID3D10BlobVtbl {
    fn default() -> Struct_ID3D10BlobVtbl { unsafe { ::std::mem::zeroed() } }
}
pub type ID3D10BlobVtbl = Struct_ID3D10BlobVtbl;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ID3D10Blob {
    pub lpVtbl: *mut Struct_ID3D10BlobVtbl,
}
impl ::std::default::Default for Struct_ID3D10Blob {
    fn default() -> Struct_ID3D10Blob { unsafe { ::std::mem::zeroed() } }
}
pub type LPD3D10BLOB = *mut Struct_ID3D10Blob;
pub type ID3DBlob = ID3D10Blob;
pub type LPD3DBLOB = *mut ID3DBlob;
pub type Enum__D3D_INCLUDE_TYPE = ::libc::c_uint;
pub const D3D_INCLUDE_LOCAL: ::libc::c_uint = 0;
pub const D3D_INCLUDE_SYSTEM: ::libc::c_uint = 1;
pub const D3D10_INCLUDE_LOCAL: ::libc::c_uint = 0;
pub const D3D10_INCLUDE_SYSTEM: ::libc::c_uint = 1;
pub const D3D_INCLUDE_FORCE_DWORD: ::libc::c_uint = 2147483647;
pub type D3D_INCLUDE_TYPE = Enum__D3D_INCLUDE_TYPE;
pub type ID3DInclude = Struct_ID3DInclude;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ID3DInclude {
    pub lpVtbl: *mut Struct_ID3DIncludeVtbl,
}
impl ::std::default::Default for Struct_ID3DInclude {
    fn default() -> Struct_ID3DInclude { unsafe { ::std::mem::zeroed() } }
}
pub type ID3DIncludeVtbl = Struct_ID3DIncludeVtbl;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ID3DIncludeVtbl {
    pub Open: ::std::option::Option<extern "C" fn
                                        (This: *mut ID3DInclude,
                                         IncludeType: D3D_INCLUDE_TYPE,
                                         pFileName: LPCSTR,
                                         pParentData: LPCVOID,
                                         ppData: *mut LPCVOID,
                                         pBytes: *mut UINT) -> HRESULT>,
    pub Close: ::std::option::Option<extern "C" fn
                                         (This: *mut ID3DInclude,
                                          pData: LPCVOID) -> HRESULT>,
}
impl ::std::default::Default for Struct_ID3DIncludeVtbl {
    fn default() -> Struct_ID3DIncludeVtbl { unsafe { ::std::mem::zeroed() } }
}
pub type LPD3DINCLUDE = *mut ID3DInclude;
pub type Enum__D3D_SHADER_VARIABLE_CLASS = ::libc::c_uint;
pub const D3D_SVC_SCALAR: ::libc::c_uint = 0;
pub const D3D_SVC_VECTOR: ::libc::c_uint = 1;
pub const D3D_SVC_MATRIX_ROWS: ::libc::c_uint = 2;
pub const D3D_SVC_MATRIX_COLUMNS: ::libc::c_uint = 3;
pub const D3D_SVC_OBJECT: ::libc::c_uint = 4;
pub const D3D_SVC_STRUCT: ::libc::c_uint = 5;
pub const D3D_SVC_INTERFACE_CLASS: ::libc::c_uint = 6;
pub const D3D_SVC_INTERFACE_POINTER: ::libc::c_uint = 7;
pub const D3D10_SVC_SCALAR: ::libc::c_uint = 0;
pub const D3D10_SVC_VECTOR: ::libc::c_uint = 1;
pub const D3D10_SVC_MATRIX_ROWS: ::libc::c_uint = 2;
pub const D3D10_SVC_MATRIX_COLUMNS: ::libc::c_uint = 3;
pub const D3D10_SVC_OBJECT: ::libc::c_uint = 4;
pub const D3D10_SVC_STRUCT: ::libc::c_uint = 5;
pub const D3D11_SVC_INTERFACE_CLASS: ::libc::c_uint = 6;
pub const D3D11_SVC_INTERFACE_POINTER: ::libc::c_uint = 7;
pub const D3D_SVC_FORCE_DWORD: ::libc::c_uint = 2147483647;
pub type D3D_SHADER_VARIABLE_CLASS = Enum__D3D_SHADER_VARIABLE_CLASS;
pub type Enum__D3D_SHADER_VARIABLE_FLAGS = ::libc::c_uint;
pub const D3D_SVF_USERPACKED: ::libc::c_uint = 1;
pub const D3D_SVF_USED: ::libc::c_uint = 2;
pub const D3D_SVF_INTERFACE_POINTER: ::libc::c_uint = 4;
pub const D3D_SVF_INTERFACE_PARAMETER: ::libc::c_uint = 8;
pub const D3D10_SVF_USERPACKED: ::libc::c_uint = 1;
pub const D3D10_SVF_USED: ::libc::c_uint = 2;
pub const D3D11_SVF_INTERFACE_POINTER: ::libc::c_uint = 4;
pub const D3D11_SVF_INTERFACE_PARAMETER: ::libc::c_uint = 8;
pub const D3D_SVF_FORCE_DWORD: ::libc::c_uint = 2147483647;
pub type D3D_SHADER_VARIABLE_FLAGS = Enum__D3D_SHADER_VARIABLE_FLAGS;
pub type Enum__D3D_SHADER_VARIABLE_TYPE = ::libc::c_uint;
pub const D3D_SVT_VOID: ::libc::c_uint = 0;
pub const D3D_SVT_BOOL: ::libc::c_uint = 1;
pub const D3D_SVT_INT: ::libc::c_uint = 2;
pub const D3D_SVT_FLOAT: ::libc::c_uint = 3;
pub const D3D_SVT_STRING: ::libc::c_uint = 4;
pub const D3D_SVT_TEXTURE: ::libc::c_uint = 5;
pub const D3D_SVT_TEXTURE1D: ::libc::c_uint = 6;
pub const D3D_SVT_TEXTURE2D: ::libc::c_uint = 7;
pub const D3D_SVT_TEXTURE3D: ::libc::c_uint = 8;
pub const D3D_SVT_TEXTURECUBE: ::libc::c_uint = 9;
pub const D3D_SVT_SAMPLER: ::libc::c_uint = 10;
pub const D3D_SVT_SAMPLER1D: ::libc::c_uint = 11;
pub const D3D_SVT_SAMPLER2D: ::libc::c_uint = 12;
pub const D3D_SVT_SAMPLER3D: ::libc::c_uint = 13;
pub const D3D_SVT_SAMPLERCUBE: ::libc::c_uint = 14;
pub const D3D_SVT_PIXELSHADER: ::libc::c_uint = 15;
pub const D3D_SVT_VERTEXSHADER: ::libc::c_uint = 16;
pub const D3D_SVT_PIXELFRAGMENT: ::libc::c_uint = 17;
pub const D3D_SVT_VERTEXFRAGMENT: ::libc::c_uint = 18;
pub const D3D_SVT_UINT: ::libc::c_uint = 19;
pub const D3D_SVT_UINT8: ::libc::c_uint = 20;
pub const D3D_SVT_GEOMETRYSHADER: ::libc::c_uint = 21;
pub const D3D_SVT_RASTERIZER: ::libc::c_uint = 22;
pub const D3D_SVT_DEPTHSTENCIL: ::libc::c_uint = 23;
pub const D3D_SVT_BLEND: ::libc::c_uint = 24;
pub const D3D_SVT_BUFFER: ::libc::c_uint = 25;
pub const D3D_SVT_CBUFFER: ::libc::c_uint = 26;
pub const D3D_SVT_TBUFFER: ::libc::c_uint = 27;
pub const D3D_SVT_TEXTURE1DARRAY: ::libc::c_uint = 28;
pub const D3D_SVT_TEXTURE2DARRAY: ::libc::c_uint = 29;
pub const D3D_SVT_RENDERTARGETVIEW: ::libc::c_uint = 30;
pub const D3D_SVT_DEPTHSTENCILVIEW: ::libc::c_uint = 31;
pub const D3D_SVT_TEXTURE2DMS: ::libc::c_uint = 32;
pub const D3D_SVT_TEXTURE2DMSARRAY: ::libc::c_uint = 33;
pub const D3D_SVT_TEXTURECUBEARRAY: ::libc::c_uint = 34;
pub const D3D_SVT_HULLSHADER: ::libc::c_uint = 35;
pub const D3D_SVT_DOMAINSHADER: ::libc::c_uint = 36;
pub const D3D_SVT_INTERFACE_POINTER: ::libc::c_uint = 37;
pub const D3D_SVT_COMPUTESHADER: ::libc::c_uint = 38;
pub const D3D_SVT_DOUBLE: ::libc::c_uint = 39;
pub const D3D_SVT_RWTEXTURE1D: ::libc::c_uint = 40;
pub const D3D_SVT_RWTEXTURE1DARRAY: ::libc::c_uint = 41;
pub const D3D_SVT_RWTEXTURE2D: ::libc::c_uint = 42;
pub const D3D_SVT_RWTEXTURE2DARRAY: ::libc::c_uint = 43;
pub const D3D_SVT_RWTEXTURE3D: ::libc::c_uint = 44;
pub const D3D_SVT_RWBUFFER: ::libc::c_uint = 45;
pub const D3D_SVT_BYTEADDRESS_BUFFER: ::libc::c_uint = 46;
pub const D3D_SVT_RWBYTEADDRESS_BUFFER: ::libc::c_uint = 47;
pub const D3D_SVT_STRUCTURED_BUFFER: ::libc::c_uint = 48;
pub const D3D_SVT_RWSTRUCTURED_BUFFER: ::libc::c_uint = 49;
pub const D3D_SVT_APPEND_STRUCTURED_BUFFER: ::libc::c_uint = 50;
pub const D3D_SVT_CONSUME_STRUCTURED_BUFFER: ::libc::c_uint = 51;
pub const D3D10_SVT_VOID: ::libc::c_uint = 0;
pub const D3D10_SVT_BOOL: ::libc::c_uint = 1;
pub const D3D10_SVT_INT: ::libc::c_uint = 2;
pub const D3D10_SVT_FLOAT: ::libc::c_uint = 3;
pub const D3D10_SVT_STRING: ::libc::c_uint = 4;
pub const D3D10_SVT_TEXTURE: ::libc::c_uint = 5;
pub const D3D10_SVT_TEXTURE1D: ::libc::c_uint = 6;
pub const D3D10_SVT_TEXTURE2D: ::libc::c_uint = 7;
pub const D3D10_SVT_TEXTURE3D: ::libc::c_uint = 8;
pub const D3D10_SVT_TEXTURECUBE: ::libc::c_uint = 9;
pub const D3D10_SVT_SAMPLER: ::libc::c_uint = 10;
pub const D3D10_SVT_SAMPLER1D: ::libc::c_uint = 11;
pub const D3D10_SVT_SAMPLER2D: ::libc::c_uint = 12;
pub const D3D10_SVT_SAMPLER3D: ::libc::c_uint = 13;
pub const D3D10_SVT_SAMPLERCUBE: ::libc::c_uint = 14;
pub const D3D10_SVT_PIXELSHADER: ::libc::c_uint = 15;
pub const D3D10_SVT_VERTEXSHADER: ::libc::c_uint = 16;
pub const D3D10_SVT_PIXELFRAGMENT: ::libc::c_uint = 17;
pub const D3D10_SVT_VERTEXFRAGMENT: ::libc::c_uint = 18;
pub const D3D10_SVT_UINT: ::libc::c_uint = 19;
pub const D3D10_SVT_UINT8: ::libc::c_uint = 20;
pub const D3D10_SVT_GEOMETRYSHADER: ::libc::c_uint = 21;
pub const D3D10_SVT_RASTERIZER: ::libc::c_uint = 22;
pub const D3D10_SVT_DEPTHSTENCIL: ::libc::c_uint = 23;
pub const D3D10_SVT_BLEND: ::libc::c_uint = 24;
pub const D3D10_SVT_BUFFER: ::libc::c_uint = 25;
pub const D3D10_SVT_CBUFFER: ::libc::c_uint = 26;
pub const D3D10_SVT_TBUFFER: ::libc::c_uint = 27;
pub const D3D10_SVT_TEXTURE1DARRAY: ::libc::c_uint = 28;
pub const D3D10_SVT_TEXTURE2DARRAY: ::libc::c_uint = 29;
pub const D3D10_SVT_RENDERTARGETVIEW: ::libc::c_uint = 30;
pub const D3D10_SVT_DEPTHSTENCILVIEW: ::libc::c_uint = 31;
pub const D3D10_SVT_TEXTURE2DMS: ::libc::c_uint = 32;
pub const D3D10_SVT_TEXTURE2DMSARRAY: ::libc::c_uint = 33;
pub const D3D10_SVT_TEXTURECUBEARRAY: ::libc::c_uint = 34;
pub const D3D11_SVT_HULLSHADER: ::libc::c_uint = 35;
pub const D3D11_SVT_DOMAINSHADER: ::libc::c_uint = 36;
pub const D3D11_SVT_INTERFACE_POINTER: ::libc::c_uint = 37;
pub const D3D11_SVT_COMPUTESHADER: ::libc::c_uint = 38;
pub const D3D11_SVT_DOUBLE: ::libc::c_uint = 39;
pub const D3D11_SVT_RWTEXTURE1D: ::libc::c_uint = 40;
pub const D3D11_SVT_RWTEXTURE1DARRAY: ::libc::c_uint = 41;
pub const D3D11_SVT_RWTEXTURE2D: ::libc::c_uint = 42;
pub const D3D11_SVT_RWTEXTURE2DARRAY: ::libc::c_uint = 43;
pub const D3D11_SVT_RWTEXTURE3D: ::libc::c_uint = 44;
pub const D3D11_SVT_RWBUFFER: ::libc::c_uint = 45;
pub const D3D11_SVT_BYTEADDRESS_BUFFER: ::libc::c_uint = 46;
pub const D3D11_SVT_RWBYTEADDRESS_BUFFER: ::libc::c_uint = 47;
pub const D3D11_SVT_STRUCTURED_BUFFER: ::libc::c_uint = 48;
pub const D3D11_SVT_RWSTRUCTURED_BUFFER: ::libc::c_uint = 49;
pub const D3D11_SVT_APPEND_STRUCTURED_BUFFER: ::libc::c_uint = 50;
pub const D3D11_SVT_CONSUME_STRUCTURED_BUFFER: ::libc::c_uint = 51;
pub const D3D_SVT_FORCE_DWORD: ::libc::c_uint = 2147483647;
pub type D3D_SHADER_VARIABLE_TYPE = Enum__D3D_SHADER_VARIABLE_TYPE;
pub type Enum__D3D_SHADER_INPUT_FLAGS = ::libc::c_uint;
pub const D3D_SIF_USERPACKED: ::libc::c_uint = 1;
pub const D3D_SIF_COMPARISON_SAMPLER: ::libc::c_uint = 2;
pub const D3D_SIF_TEXTURE_COMPONENT_0: ::libc::c_uint = 4;
pub const D3D_SIF_TEXTURE_COMPONENT_1: ::libc::c_uint = 8;
pub const D3D_SIF_TEXTURE_COMPONENTS: ::libc::c_uint = 12;
pub const D3D10_SIF_USERPACKED: ::libc::c_uint = 1;
pub const D3D10_SIF_COMPARISON_SAMPLER: ::libc::c_uint = 2;
pub const D3D10_SIF_TEXTURE_COMPONENT_0: ::libc::c_uint = 4;
pub const D3D10_SIF_TEXTURE_COMPONENT_1: ::libc::c_uint = 8;
pub const D3D10_SIF_TEXTURE_COMPONENTS: ::libc::c_uint = 12;
pub const D3D_SIF_FORCE_DWORD: ::libc::c_uint = 2147483647;
pub type D3D_SHADER_INPUT_FLAGS = Enum__D3D_SHADER_INPUT_FLAGS;
pub type Enum__D3D_SHADER_INPUT_TYPE = ::libc::c_uint;
pub const D3D_SIT_CBUFFER: ::libc::c_uint = 0;
pub const D3D_SIT_TBUFFER: ::libc::c_uint = 1;
pub const D3D_SIT_TEXTURE: ::libc::c_uint = 2;
pub const D3D_SIT_SAMPLER: ::libc::c_uint = 3;
pub const D3D_SIT_UAV_RWTYPED: ::libc::c_uint = 4;
pub const D3D_SIT_STRUCTURED: ::libc::c_uint = 5;
pub const D3D_SIT_UAV_RWSTRUCTURED: ::libc::c_uint = 6;
pub const D3D_SIT_BYTEADDRESS: ::libc::c_uint = 7;
pub const D3D_SIT_UAV_RWBYTEADDRESS: ::libc::c_uint = 8;
pub const D3D_SIT_UAV_APPEND_STRUCTURED: ::libc::c_uint = 9;
pub const D3D_SIT_UAV_CONSUME_STRUCTURED: ::libc::c_uint = 10;
pub const D3D_SIT_UAV_RWSTRUCTURED_WITH_COUNTER: ::libc::c_uint = 11;
pub const D3D10_SIT_CBUFFER: ::libc::c_uint = 0;
pub const D3D10_SIT_TBUFFER: ::libc::c_uint = 1;
pub const D3D10_SIT_TEXTURE: ::libc::c_uint = 2;
pub const D3D10_SIT_SAMPLER: ::libc::c_uint = 3;
pub const D3D11_SIT_UAV_RWTYPED: ::libc::c_uint = 4;
pub const D3D11_SIT_STRUCTURED: ::libc::c_uint = 5;
pub const D3D11_SIT_UAV_RWSTRUCTURED: ::libc::c_uint = 6;
pub const D3D11_SIT_BYTEADDRESS: ::libc::c_uint = 7;
pub const D3D11_SIT_UAV_RWBYTEADDRESS: ::libc::c_uint = 8;
pub const D3D11_SIT_UAV_APPEND_STRUCTURED: ::libc::c_uint = 9;
pub const D3D11_SIT_UAV_CONSUME_STRUCTURED: ::libc::c_uint = 10;
pub const D3D11_SIT_UAV_RWSTRUCTURED_WITH_COUNTER: ::libc::c_uint = 11;
pub type D3D_SHADER_INPUT_TYPE = Enum__D3D_SHADER_INPUT_TYPE;
pub type Enum__D3D_SHADER_CBUFFER_FLAGS = ::libc::c_uint;
pub const D3D_CBF_USERPACKED: ::libc::c_uint = 1;
pub const D3D10_CBF_USERPACKED: ::libc::c_uint = 1;
pub const D3D_CBF_FORCE_DWORD: ::libc::c_uint = 2147483647;
pub type D3D_SHADER_CBUFFER_FLAGS = Enum__D3D_SHADER_CBUFFER_FLAGS;
pub type Enum__D3D_CBUFFER_TYPE = ::libc::c_uint;
pub const D3D_CT_CBUFFER: ::libc::c_uint = 0;
pub const D3D_CT_TBUFFER: ::libc::c_uint = 1;
pub const D3D_CT_INTERFACE_POINTERS: ::libc::c_uint = 2;
pub const D3D_CT_RESOURCE_BIND_INFO: ::libc::c_uint = 3;
pub const D3D10_CT_CBUFFER: ::libc::c_uint = 0;
pub const D3D10_CT_TBUFFER: ::libc::c_uint = 1;
pub const D3D11_CT_CBUFFER: ::libc::c_uint = 0;
pub const D3D11_CT_TBUFFER: ::libc::c_uint = 1;
pub const D3D11_CT_INTERFACE_POINTERS: ::libc::c_uint = 2;
pub const D3D11_CT_RESOURCE_BIND_INFO: ::libc::c_uint = 3;
pub type D3D_CBUFFER_TYPE = Enum__D3D_CBUFFER_TYPE;
pub type Enum_D3D_NAME = ::libc::c_uint;
pub const D3D_NAME_UNDEFINED: ::libc::c_uint = 0;
pub const D3D_NAME_POSITION: ::libc::c_uint = 1;
pub const D3D_NAME_CLIP_DISTANCE: ::libc::c_uint = 2;
pub const D3D_NAME_CULL_DISTANCE: ::libc::c_uint = 3;
pub const D3D_NAME_RENDER_TARGET_ARRAY_INDEX: ::libc::c_uint = 4;
pub const D3D_NAME_VIEWPORT_ARRAY_INDEX: ::libc::c_uint = 5;
pub const D3D_NAME_VERTEX_ID: ::libc::c_uint = 6;
pub const D3D_NAME_PRIMITIVE_ID: ::libc::c_uint = 7;
pub const D3D_NAME_INSTANCE_ID: ::libc::c_uint = 8;
pub const D3D_NAME_IS_FRONT_FACE: ::libc::c_uint = 9;
pub const D3D_NAME_SAMPLE_INDEX: ::libc::c_uint = 10;
pub const D3D_NAME_FINAL_QUAD_EDGE_TESSFACTOR: ::libc::c_uint = 11;
pub const D3D_NAME_FINAL_QUAD_INSIDE_TESSFACTOR: ::libc::c_uint = 12;
pub const D3D_NAME_FINAL_TRI_EDGE_TESSFACTOR: ::libc::c_uint = 13;
pub const D3D_NAME_FINAL_TRI_INSIDE_TESSFACTOR: ::libc::c_uint = 14;
pub const D3D_NAME_FINAL_LINE_DETAIL_TESSFACTOR: ::libc::c_uint = 15;
pub const D3D_NAME_FINAL_LINE_DENSITY_TESSFACTOR: ::libc::c_uint = 16;
pub const D3D_NAME_TARGET: ::libc::c_uint = 64;
pub const D3D_NAME_DEPTH: ::libc::c_uint = 65;
pub const D3D_NAME_COVERAGE: ::libc::c_uint = 66;
pub const D3D_NAME_DEPTH_GREATER_EQUAL: ::libc::c_uint = 67;
pub const D3D_NAME_DEPTH_LESS_EQUAL: ::libc::c_uint = 68;
pub const D3D10_NAME_UNDEFINED: ::libc::c_uint = 0;
pub const D3D10_NAME_POSITION: ::libc::c_uint = 1;
pub const D3D10_NAME_CLIP_DISTANCE: ::libc::c_uint = 2;
pub const D3D10_NAME_CULL_DISTANCE: ::libc::c_uint = 3;
pub const D3D10_NAME_RENDER_TARGET_ARRAY_INDEX: ::libc::c_uint = 4;
pub const D3D10_NAME_VIEWPORT_ARRAY_INDEX: ::libc::c_uint = 5;
pub const D3D10_NAME_VERTEX_ID: ::libc::c_uint = 6;
pub const D3D10_NAME_PRIMITIVE_ID: ::libc::c_uint = 7;
pub const D3D10_NAME_INSTANCE_ID: ::libc::c_uint = 8;
pub const D3D10_NAME_IS_FRONT_FACE: ::libc::c_uint = 9;
pub const D3D10_NAME_SAMPLE_INDEX: ::libc::c_uint = 10;
pub const D3D10_NAME_TARGET: ::libc::c_uint = 64;
pub const D3D10_NAME_DEPTH: ::libc::c_uint = 65;
pub const D3D10_NAME_COVERAGE: ::libc::c_uint = 66;
pub const D3D11_NAME_FINAL_QUAD_EDGE_TESSFACTOR: ::libc::c_uint = 11;
pub const D3D11_NAME_FINAL_QUAD_INSIDE_TESSFACTOR: ::libc::c_uint = 12;
pub const D3D11_NAME_FINAL_TRI_EDGE_TESSFACTOR: ::libc::c_uint = 13;
pub const D3D11_NAME_FINAL_TRI_INSIDE_TESSFACTOR: ::libc::c_uint = 14;
pub const D3D11_NAME_FINAL_LINE_DETAIL_TESSFACTOR: ::libc::c_uint = 15;
pub const D3D11_NAME_FINAL_LINE_DENSITY_TESSFACTOR: ::libc::c_uint = 16;
pub const D3D11_NAME_DEPTH_GREATER_EQUAL: ::libc::c_uint = 67;
pub const D3D11_NAME_DEPTH_LESS_EQUAL: ::libc::c_uint = 68;
pub type D3D_NAME = Enum_D3D_NAME;
pub type Enum_D3D_RESOURCE_RETURN_TYPE = ::libc::c_uint;
pub const D3D_RETURN_TYPE_UNORM: ::libc::c_uint = 1;
pub const D3D_RETURN_TYPE_SNORM: ::libc::c_uint = 2;
pub const D3D_RETURN_TYPE_SINT: ::libc::c_uint = 3;
pub const D3D_RETURN_TYPE_UINT: ::libc::c_uint = 4;
pub const D3D_RETURN_TYPE_FLOAT: ::libc::c_uint = 5;
pub const D3D_RETURN_TYPE_MIXED: ::libc::c_uint = 6;
pub const D3D_RETURN_TYPE_DOUBLE: ::libc::c_uint = 7;
pub const D3D_RETURN_TYPE_CONTINUED: ::libc::c_uint = 8;
pub const D3D10_RETURN_TYPE_UNORM: ::libc::c_uint = 1;
pub const D3D10_RETURN_TYPE_SNORM: ::libc::c_uint = 2;
pub const D3D10_RETURN_TYPE_SINT: ::libc::c_uint = 3;
pub const D3D10_RETURN_TYPE_UINT: ::libc::c_uint = 4;
pub const D3D10_RETURN_TYPE_FLOAT: ::libc::c_uint = 5;
pub const D3D10_RETURN_TYPE_MIXED: ::libc::c_uint = 6;
pub const D3D11_RETURN_TYPE_UNORM: ::libc::c_uint = 1;
pub const D3D11_RETURN_TYPE_SNORM: ::libc::c_uint = 2;
pub const D3D11_RETURN_TYPE_SINT: ::libc::c_uint = 3;
pub const D3D11_RETURN_TYPE_UINT: ::libc::c_uint = 4;
pub const D3D11_RETURN_TYPE_FLOAT: ::libc::c_uint = 5;
pub const D3D11_RETURN_TYPE_MIXED: ::libc::c_uint = 6;
pub const D3D11_RETURN_TYPE_DOUBLE: ::libc::c_uint = 7;
pub const D3D11_RETURN_TYPE_CONTINUED: ::libc::c_uint = 8;
pub type D3D_RESOURCE_RETURN_TYPE = Enum_D3D_RESOURCE_RETURN_TYPE;
pub type Enum_D3D_REGISTER_COMPONENT_TYPE = ::libc::c_uint;
pub const D3D_REGISTER_COMPONENT_UNKNOWN: ::libc::c_uint = 0;
pub const D3D_REGISTER_COMPONENT_UINT32: ::libc::c_uint = 1;
pub const D3D_REGISTER_COMPONENT_SINT32: ::libc::c_uint = 2;
pub const D3D_REGISTER_COMPONENT_FLOAT32: ::libc::c_uint = 3;
pub const D3D10_REGISTER_COMPONENT_UNKNOWN: ::libc::c_uint = 0;
pub const D3D10_REGISTER_COMPONENT_UINT32: ::libc::c_uint = 1;
pub const D3D10_REGISTER_COMPONENT_SINT32: ::libc::c_uint = 2;
pub const D3D10_REGISTER_COMPONENT_FLOAT32: ::libc::c_uint = 3;
pub type D3D_REGISTER_COMPONENT_TYPE = Enum_D3D_REGISTER_COMPONENT_TYPE;
pub type Enum_D3D_TESSELLATOR_DOMAIN = ::libc::c_uint;
pub const D3D_TESSELLATOR_DOMAIN_UNDEFINED: ::libc::c_uint = 0;
pub const D3D_TESSELLATOR_DOMAIN_ISOLINE: ::libc::c_uint = 1;
pub const D3D_TESSELLATOR_DOMAIN_TRI: ::libc::c_uint = 2;
pub const D3D_TESSELLATOR_DOMAIN_QUAD: ::libc::c_uint = 3;
pub const D3D11_TESSELLATOR_DOMAIN_UNDEFINED: ::libc::c_uint = 0;
pub const D3D11_TESSELLATOR_DOMAIN_ISOLINE: ::libc::c_uint = 1;
pub const D3D11_TESSELLATOR_DOMAIN_TRI: ::libc::c_uint = 2;
pub const D3D11_TESSELLATOR_DOMAIN_QUAD: ::libc::c_uint = 3;
pub type D3D_TESSELLATOR_DOMAIN = Enum_D3D_TESSELLATOR_DOMAIN;
pub type Enum_D3D_TESSELLATOR_PARTITIONING = ::libc::c_uint;
pub const D3D_TESSELLATOR_PARTITIONING_UNDEFINED: ::libc::c_uint = 0;
pub const D3D_TESSELLATOR_PARTITIONING_INTEGER: ::libc::c_uint = 1;
pub const D3D_TESSELLATOR_PARTITIONING_POW2: ::libc::c_uint = 2;
pub const D3D_TESSELLATOR_PARTITIONING_FRACTIONAL_ODD: ::libc::c_uint = 3;
pub const D3D_TESSELLATOR_PARTITIONING_FRACTIONAL_EVEN: ::libc::c_uint = 4;
pub const D3D11_TESSELLATOR_PARTITIONING_UNDEFINED: ::libc::c_uint = 0;
pub const D3D11_TESSELLATOR_PARTITIONING_INTEGER: ::libc::c_uint = 1;
pub const D3D11_TESSELLATOR_PARTITIONING_POW2: ::libc::c_uint = 2;
pub const D3D11_TESSELLATOR_PARTITIONING_FRACTIONAL_ODD: ::libc::c_uint = 3;
pub const D3D11_TESSELLATOR_PARTITIONING_FRACTIONAL_EVEN: ::libc::c_uint = 4;
pub type D3D_TESSELLATOR_PARTITIONING = Enum_D3D_TESSELLATOR_PARTITIONING;
pub type Enum_D3D_TESSELLATOR_OUTPUT_PRIMITIVE = ::libc::c_uint;
pub const D3D_TESSELLATOR_OUTPUT_UNDEFINED: ::libc::c_uint = 0;
pub const D3D_TESSELLATOR_OUTPUT_POINT: ::libc::c_uint = 1;
pub const D3D_TESSELLATOR_OUTPUT_LINE: ::libc::c_uint = 2;
pub const D3D_TESSELLATOR_OUTPUT_TRIANGLE_CW: ::libc::c_uint = 3;
pub const D3D_TESSELLATOR_OUTPUT_TRIANGLE_CCW: ::libc::c_uint = 4;
pub const D3D11_TESSELLATOR_OUTPUT_UNDEFINED: ::libc::c_uint = 0;
pub const D3D11_TESSELLATOR_OUTPUT_POINT: ::libc::c_uint = 1;
pub const D3D11_TESSELLATOR_OUTPUT_LINE: ::libc::c_uint = 2;
pub const D3D11_TESSELLATOR_OUTPUT_TRIANGLE_CW: ::libc::c_uint = 3;
pub const D3D11_TESSELLATOR_OUTPUT_TRIANGLE_CCW: ::libc::c_uint = 4;
pub type D3D_TESSELLATOR_OUTPUT_PRIMITIVE =
    Enum_D3D_TESSELLATOR_OUTPUT_PRIMITIVE;
extern "C" {
    pub static IID_ID3D10Blob: IID;
    pub static mut __MIDL_itf_d3dcommon_0000_0000_v0_0_c_ifspec:
               RPC_IF_HANDLE;
    pub static mut __MIDL_itf_d3dcommon_0000_0000_v0_0_s_ifspec:
               RPC_IF_HANDLE;
    pub static WKPDID_D3DDebugObjectName: GUID;
    pub static mut __MIDL_itf_d3dcommon_0000_0001_v0_0_c_ifspec:
               RPC_IF_HANDLE;
    pub static mut __MIDL_itf_d3dcommon_0000_0001_v0_0_s_ifspec:
               RPC_IF_HANDLE;
}
