/* automatically generated by rust-bindgen */

extern "C" {
    pub fn D3DXCreatePolygon(pDevice: LPDIRECT3DDEVICE9, Length: FLOAT,
                             Sides: UINT, ppMesh: *mut LPD3DXMESH,
                             ppAdjacency: *mut LPD3DXBUFFER) -> HRESULT;
    pub fn D3DXCreateBox(pDevice: LPDIRECT3DDEVICE9, Width: FLOAT,
                         Height: FLOAT, Depth: FLOAT, ppMesh: *mut LPD3DXMESH,
                         ppAdjacency: *mut LPD3DXBUFFER) -> HRESULT;
    pub fn D3DXCreateCylinder(pDevice: LPDIRECT3DDEVICE9, Radius1: FLOAT,
                              Radius2: FLOAT, Length: FLOAT, Slices: UINT,
                              Stacks: UINT, ppMesh: *mut LPD3DXMESH,
                              ppAdjacency: *mut LPD3DXBUFFER) -> HRESULT;
    pub fn D3DXCreateSphere(pDevice: LPDIRECT3DDEVICE9, Radius: FLOAT,
                            Slices: UINT, Stacks: UINT,
                            ppMesh: *mut LPD3DXMESH,
                            ppAdjacency: *mut LPD3DXBUFFER) -> HRESULT;
    pub fn D3DXCreateTorus(pDevice: LPDIRECT3DDEVICE9, InnerRadius: FLOAT,
                           OuterRadius: FLOAT, Sides: UINT, Rings: UINT,
                           ppMesh: *mut LPD3DXMESH,
                           ppAdjacency: *mut LPD3DXBUFFER) -> HRESULT;
    pub fn D3DXCreateTeapot(pDevice: LPDIRECT3DDEVICE9,
                            ppMesh: *mut LPD3DXMESH,
                            ppAdjacency: *mut LPD3DXBUFFER) -> HRESULT;
    pub fn D3DXCreateTextA(pDevice: LPDIRECT3DDEVICE9, hDC: HDC,
                           pText: LPCSTR, Deviation: FLOAT, Extrusion: FLOAT,
                           ppMesh: *mut LPD3DXMESH,
                           ppAdjacency: *mut LPD3DXBUFFER,
                           pGlyphMetrics: LPGLYPHMETRICSFLOAT) -> HRESULT;
    pub fn D3DXCreateTextW(pDevice: LPDIRECT3DDEVICE9, hDC: HDC,
                           pText: LPCWSTR, Deviation: FLOAT, Extrusion: FLOAT,
                           ppMesh: *mut LPD3DXMESH,
                           ppAdjacency: *mut LPD3DXBUFFER,
                           pGlyphMetrics: LPGLYPHMETRICSFLOAT) -> HRESULT;
}
