/* automatically generated by rust-bindgen */

pub type D3DXF_FILEFORMAT = DWORD;
pub type D3DXF_FILESAVEOPTIONS = DWORD;
pub type D3DXF_FILELOADOPTIONS = DWORD;
#[repr(C)]
#[derive(Copy)]
pub struct Struct__D3DXF_FILELOADRESOURCE {
    pub hModule: HMODULE,
    pub lpName: LPCSTR,
    pub lpType: LPCSTR,
}
impl ::std::default::Default for Struct__D3DXF_FILELOADRESOURCE {
    fn default() -> Struct__D3DXF_FILELOADRESOURCE {
        unsafe { ::std::mem::zeroed() }
    }
}
pub type D3DXF_FILELOADRESOURCE = Struct__D3DXF_FILELOADRESOURCE;
#[repr(C)]
#[derive(Copy)]
pub struct Struct__D3DXF_FILELOADMEMORY {
    pub lpMemory: LPCVOID,
    pub dSize: SIZE_T,
}
impl ::std::default::Default for Struct__D3DXF_FILELOADMEMORY {
    fn default() -> Struct__D3DXF_FILELOADMEMORY {
        unsafe { ::std::mem::zeroed() }
    }
}
pub type D3DXF_FILELOADMEMORY = Struct__D3DXF_FILELOADMEMORY;
pub type ID3DXFile = Struct_ID3DXFile;
pub type ID3DXFileSaveObject = Struct_ID3DXFileSaveObject;
pub type ID3DXFileSaveData = Struct_ID3DXFileSaveData;
pub type ID3DXFileEnumObject = Struct_ID3DXFileEnumObject;
pub type ID3DXFileData = Struct_ID3DXFileData;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ID3DXFile {
    pub lpVtbl: *mut Struct_ID3DXFileVtbl,
}
impl ::std::default::Default for Struct_ID3DXFile {
    fn default() -> Struct_ID3DXFile { unsafe { ::std::mem::zeroed() } }
}
pub type ID3DXFileVtbl = Struct_ID3DXFileVtbl;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ID3DXFileVtbl {
    pub QueryInterface: ::std::option::Option<extern "C" fn
                                                  (This: *mut ID3DXFile,
                                                   arg1: *const IID,
                                                   arg2: *mut LPVOID)
                                                  -> HRESULT>,
    pub AddRef: ::std::option::Option<extern "C" fn(This: *mut ID3DXFile)
                                          -> ULONG>,
    pub Release: ::std::option::Option<extern "C" fn(This: *mut ID3DXFile)
                                           -> ULONG>,
    pub CreateEnumObject: ::std::option::Option<extern "C" fn
                                                    (This: *mut ID3DXFile,
                                                     arg1: LPCVOID,
                                                     arg2:
                                                         D3DXF_FILELOADOPTIONS,
                                                     arg3:
                                                         *mut *mut ID3DXFileEnumObject)
                                                    -> HRESULT>,
    pub CreateSaveObject: ::std::option::Option<extern "C" fn
                                                    (This: *mut ID3DXFile,
                                                     arg1: LPCVOID,
                                                     arg2:
                                                         D3DXF_FILESAVEOPTIONS,
                                                     arg3: D3DXF_FILEFORMAT,
                                                     arg4:
                                                         *mut *mut ID3DXFileSaveObject)
                                                    -> HRESULT>,
    pub RegisterTemplates: ::std::option::Option<extern "C" fn
                                                     (This: *mut ID3DXFile,
                                                      arg1: LPCVOID,
                                                      arg2: SIZE_T)
                                                     -> HRESULT>,
    pub RegisterEnumTemplates: ::std::option::Option<extern "C" fn
                                                         (This:
                                                              *mut ID3DXFile,
                                                          arg1:
                                                              *mut ID3DXFileEnumObject)
                                                         -> HRESULT>,
}
impl ::std::default::Default for Struct_ID3DXFileVtbl {
    fn default() -> Struct_ID3DXFileVtbl { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ID3DXFileSaveObject {
    pub lpVtbl: *mut Struct_ID3DXFileSaveObjectVtbl,
}
impl ::std::default::Default for Struct_ID3DXFileSaveObject {
    fn default() -> Struct_ID3DXFileSaveObject {
        unsafe { ::std::mem::zeroed() }
    }
}
pub type ID3DXFileSaveObjectVtbl = Struct_ID3DXFileSaveObjectVtbl;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ID3DXFileSaveObjectVtbl {
    pub QueryInterface: ::std::option::Option<extern "C" fn
                                                  (This:
                                                       *mut ID3DXFileSaveObject,
                                                   arg1: *const IID,
                                                   arg2: *mut LPVOID)
                                                  -> HRESULT>,
    pub AddRef: ::std::option::Option<extern "C" fn
                                          (This: *mut ID3DXFileSaveObject)
                                          -> ULONG>,
    pub Release: ::std::option::Option<extern "C" fn
                                           (This: *mut ID3DXFileSaveObject)
                                           -> ULONG>,
    pub GetFile: ::std::option::Option<extern "C" fn
                                           (This: *mut ID3DXFileSaveObject,
                                            arg1: *mut *mut ID3DXFile)
                                           -> HRESULT>,
    pub AddDataObject: ::std::option::Option<extern "C" fn
                                                 (This:
                                                      *mut ID3DXFileSaveObject,
                                                  arg1: *const GUID,
                                                  arg2: LPCSTR,
                                                  arg3: *const GUID,
                                                  arg4: SIZE_T, arg5: LPCVOID,
                                                  arg6:
                                                      *mut *mut ID3DXFileSaveData)
                                                 -> HRESULT>,
    pub Save: ::std::option::Option<extern "C" fn
                                        (This: *mut ID3DXFileSaveObject)
                                        -> HRESULT>,
}
impl ::std::default::Default for Struct_ID3DXFileSaveObjectVtbl {
    fn default() -> Struct_ID3DXFileSaveObjectVtbl {
        unsafe { ::std::mem::zeroed() }
    }
}
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ID3DXFileSaveData {
    pub lpVtbl: *mut Struct_ID3DXFileSaveDataVtbl,
}
impl ::std::default::Default for Struct_ID3DXFileSaveData {
    fn default() -> Struct_ID3DXFileSaveData {
        unsafe { ::std::mem::zeroed() }
    }
}
pub type ID3DXFileSaveDataVtbl = Struct_ID3DXFileSaveDataVtbl;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ID3DXFileSaveDataVtbl {
    pub QueryInterface: ::std::option::Option<extern "C" fn
                                                  (This:
                                                       *mut ID3DXFileSaveData,
                                                   arg1: *const IID,
                                                   arg2: *mut LPVOID)
                                                  -> HRESULT>,
    pub AddRef: ::std::option::Option<extern "C" fn
                                          (This: *mut ID3DXFileSaveData)
                                          -> ULONG>,
    pub Release: ::std::option::Option<extern "C" fn
                                           (This: *mut ID3DXFileSaveData)
                                           -> ULONG>,
    pub GetSave: ::std::option::Option<extern "C" fn
                                           (This: *mut ID3DXFileSaveData,
                                            arg1:
                                                *mut *mut ID3DXFileSaveObject)
                                           -> HRESULT>,
    pub GetName: ::std::option::Option<extern "C" fn
                                           (This: *mut ID3DXFileSaveData,
                                            arg1: LPSTR, arg2: *mut SIZE_T)
                                           -> HRESULT>,
    pub GetId: ::std::option::Option<extern "C" fn
                                         (This: *mut ID3DXFileSaveData,
                                          arg1: LPGUID) -> HRESULT>,
    pub GetType: ::std::option::Option<extern "C" fn
                                           (This: *mut ID3DXFileSaveData,
                                            arg1: *mut GUID) -> HRESULT>,
    pub AddDataObject: ::std::option::Option<extern "C" fn
                                                 (This:
                                                      *mut ID3DXFileSaveData,
                                                  arg1: *const GUID,
                                                  arg2: LPCSTR,
                                                  arg3: *const GUID,
                                                  arg4: SIZE_T, arg5: LPCVOID,
                                                  arg6:
                                                      *mut *mut ID3DXFileSaveData)
                                                 -> HRESULT>,
    pub AddDataReference: ::std::option::Option<extern "C" fn
                                                    (This:
                                                         *mut ID3DXFileSaveData,
                                                     arg1: LPCSTR,
                                                     arg2: *const GUID)
                                                    -> HRESULT>,
}
impl ::std::default::Default for Struct_ID3DXFileSaveDataVtbl {
    fn default() -> Struct_ID3DXFileSaveDataVtbl {
        unsafe { ::std::mem::zeroed() }
    }
}
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ID3DXFileEnumObject {
    pub lpVtbl: *mut Struct_ID3DXFileEnumObjectVtbl,
}
impl ::std::default::Default for Struct_ID3DXFileEnumObject {
    fn default() -> Struct_ID3DXFileEnumObject {
        unsafe { ::std::mem::zeroed() }
    }
}
pub type ID3DXFileEnumObjectVtbl = Struct_ID3DXFileEnumObjectVtbl;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ID3DXFileEnumObjectVtbl {
    pub QueryInterface: ::std::option::Option<extern "C" fn
                                                  (This:
                                                       *mut ID3DXFileEnumObject,
                                                   arg1: *const IID,
                                                   arg2: *mut LPVOID)
                                                  -> HRESULT>,
    pub AddRef: ::std::option::Option<extern "C" fn
                                          (This: *mut ID3DXFileEnumObject)
                                          -> ULONG>,
    pub Release: ::std::option::Option<extern "C" fn
                                           (This: *mut ID3DXFileEnumObject)
                                           -> ULONG>,
    pub GetFile: ::std::option::Option<extern "C" fn
                                           (This: *mut ID3DXFileEnumObject,
                                            arg1: *mut *mut ID3DXFile)
                                           -> HRESULT>,
    pub GetChildren: ::std::option::Option<extern "C" fn
                                               (This:
                                                    *mut ID3DXFileEnumObject,
                                                arg1: *mut SIZE_T)
                                               -> HRESULT>,
    pub GetChild: ::std::option::Option<extern "C" fn
                                            (This: *mut ID3DXFileEnumObject,
                                             arg1: SIZE_T,
                                             arg2: *mut *mut ID3DXFileData)
                                            -> HRESULT>,
    pub GetDataObjectById: ::std::option::Option<extern "C" fn
                                                     (This:
                                                          *mut ID3DXFileEnumObject,
                                                      arg1: *const GUID,
                                                      arg2:
                                                          *mut *mut ID3DXFileData)
                                                     -> HRESULT>,
    pub GetDataObjectByName: ::std::option::Option<extern "C" fn
                                                       (This:
                                                            *mut ID3DXFileEnumObject,
                                                        arg1: LPCSTR,
                                                        arg2:
                                                            *mut *mut ID3DXFileData)
                                                       -> HRESULT>,
}
impl ::std::default::Default for Struct_ID3DXFileEnumObjectVtbl {
    fn default() -> Struct_ID3DXFileEnumObjectVtbl {
        unsafe { ::std::mem::zeroed() }
    }
}
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ID3DXFileData {
    pub lpVtbl: *mut Struct_ID3DXFileDataVtbl,
}
impl ::std::default::Default for Struct_ID3DXFileData {
    fn default() -> Struct_ID3DXFileData { unsafe { ::std::mem::zeroed() } }
}
pub type ID3DXFileDataVtbl = Struct_ID3DXFileDataVtbl;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_ID3DXFileDataVtbl {
    pub QueryInterface: ::std::option::Option<extern "C" fn
                                                  (This: *mut ID3DXFileData,
                                                   arg1: *const IID,
                                                   arg2: *mut LPVOID)
                                                  -> HRESULT>,
    pub AddRef: ::std::option::Option<extern "C" fn(This: *mut ID3DXFileData)
                                          -> ULONG>,
    pub Release: ::std::option::Option<extern "C" fn(This: *mut ID3DXFileData)
                                           -> ULONG>,
    pub GetEnum: ::std::option::Option<extern "C" fn
                                           (This: *mut ID3DXFileData,
                                            arg1:
                                                *mut *mut ID3DXFileEnumObject)
                                           -> HRESULT>,
    pub GetName: ::std::option::Option<extern "C" fn
                                           (This: *mut ID3DXFileData,
                                            arg1: LPSTR, arg2: *mut SIZE_T)
                                           -> HRESULT>,
    pub GetId: ::std::option::Option<extern "C" fn
                                         (This: *mut ID3DXFileData,
                                          arg1: LPGUID) -> HRESULT>,
    pub Lock: ::std::option::Option<extern "C" fn
                                        (This: *mut ID3DXFileData,
                                         arg1: *mut SIZE_T,
                                         arg2: *mut LPCVOID) -> HRESULT>,
    pub Unlock: ::std::option::Option<extern "C" fn(This: *mut ID3DXFileData)
                                          -> HRESULT>,
    pub GetType: ::std::option::Option<extern "C" fn
                                           (This: *mut ID3DXFileData,
                                            arg1: *mut GUID) -> HRESULT>,
    pub IsReference: ::std::option::Option<extern "C" fn
                                               (This: *mut ID3DXFileData)
                                               -> BOOL>,
    pub GetChildren: ::std::option::Option<extern "C" fn
                                               (This: *mut ID3DXFileData,
                                                arg1: *mut SIZE_T)
                                               -> HRESULT>,
    pub GetChild: ::std::option::Option<extern "C" fn
                                            (This: *mut ID3DXFileData,
                                             arg1: SIZE_T,
                                             arg2: *mut *mut ID3DXFileData)
                                            -> HRESULT>,
}
impl ::std::default::Default for Struct_ID3DXFileDataVtbl {
    fn default() -> Struct_ID3DXFileDataVtbl {
        unsafe { ::std::mem::zeroed() }
    }
}
pub type LPD3DXFILE = *mut Struct_ID3DXFile;
pub type LPLPD3DXFILE = *mut *mut Struct_ID3DXFile;
pub type LPD3DXFILEENUMOBJECT = *mut Struct_ID3DXFileEnumObject;
pub type LPLPD3DXFILEENUMOBJECT = *mut *mut Struct_ID3DXFileEnumObject;
pub type LPD3DXFILESAVEOBJECT = *mut Struct_ID3DXFileSaveObject;
pub type LPLPD3DXFILESAVEOBJECT = *mut *mut Struct_ID3DXFileSaveObject;
pub type LPD3DXFILEDATA = *mut Struct_ID3DXFileData;
pub type LPLPD3DXFILEDATA = *mut *mut Struct_ID3DXFileData;
pub type LPD3DXFILESAVEDATA = *mut Struct_ID3DXFileSaveData;
pub type LPLPD3DXFILESAVEDATA = *mut *mut Struct_ID3DXFileSaveData;
extern "C" {
    pub static IID_ID3DXFile: GUID;
    pub static IID_ID3DXFileSaveObject: GUID;
    pub static IID_ID3DXFileSaveData: GUID;
    pub static IID_ID3DXFileEnumObject: GUID;
    pub static IID_ID3DXFileData: GUID;
}
extern "C" {
    pub fn D3DXFileCreate(lplpDirectXFile: *mut *mut ID3DXFile) -> HRESULT;
}
