/* automatically generated by rust-bindgen */

pub type Enum_DWRITE_MEASURING_MODE = ::libc::c_uint;
pub const DWRITE_MEASURING_MODE_NATURAL: ::libc::c_uint = 0;
pub const DWRITE_MEASURING_MODE_GDI_CLASSIC: ::libc::c_uint = 1;
pub const DWRITE_MEASURING_MODE_GDI_NATURAL: ::libc::c_uint = 2;
pub type DWRITE_MEASURING_MODE = Enum_DWRITE_MEASURING_MODE;
